## Bronze

### Preprocessing and Ingestion

In [ ]:


%run ./preprocessing/EDA_Notebook_Pump_Bronze_01_Preprocessing.ipynb

2026-04-20 14:45:01,041 | INFO | capstone.bronze | Bronze stage starting
2026-04-20 14:45:01,043 | INFO | capstone.bronze | Project Root Path Loaded: /workspace
2026-04-20 14:45:01,046 | INFO | capstone.bronze | Project Logging Path Loaded: /workspace/logs
2026-04-20 14:45:01,047 | INFO | capstone.bronze | Project Artifacts Path Loaded: /workspace/artifacts
2026-04-20 14:45:01,049 | INFO | capstone.bronze | Project Notebooks Path Loaded: /workspace/notebooks
2026-04-20 14:45:01,050 | INFO | capstone.bronze | Project Truths Path Loaded: /workspace/artifacts/truths
2026-04-20 14:45:01,052 | INFO | capstone.bronze | Project Data Path Loaded: /workspace/data
2026-04-20 14:45:01,053 | INFO | capstone.bronze | Data Bronze Path Loaded: /workspace/data/bronze
2026-04-20 14:45:01,054 | INFO | capstone.bronze | Data Bronze Training Path Loaded: /workspace/data/bronze/train
2026-04-20 14:45:01,056 | INFO | capstone.bronze | Data Bronze Testing Path Loaded: /workspace/data/bronze/test
git root error: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: detected dubious ownership in repository at '/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /workspace'
git root error: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: detected dubious ownership in repository at '/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /workspace'
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: dcoo230 (dcoo230-western-governors-university). Use `wandb login --relogin` to force relogin

2026-04-20 14:45:05,560 | INFO | capstone.bronze | W&B initialized: bronze__001
2026-04-20 14:45:05,566 | INFO | capstone.file_io | Loading Data file: /workspace/data/raw/pump_sensor_data/sensor.csv
2026-04-20 14:45:09,210 | INFO | capstone.file_io | Loaded Data File: sensor.csv | shape=(220320, 55) | columns=['Unnamed: 0', 'timestamp', 'sensor_00', 'sensor_01', 'sensor_02', 'sensor_03', 'sensor_04', 'sensor_05', 'sensor_06', 'sensor_07', 'sensor_08', 'sensor_09', 'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21', 'sensor_22', 'sensor_23', 'sensor_24', 'sensor_25', 'sensor_26', 'sensor_27', 'sensor_28', 'sensor_29', 'sensor_30', 'sensor_31', 'sensor_32', 'sensor_33', 'sensor_34', 'sensor_35', 'sensor_36', 'sensor_37', 'sensor_38', 'sensor_39', 'sensor_40', 'sensor_41', 'sensor_42', 'sensor_43', 'sensor_44', 'sensor_45', 'sensor_46', 'sensor_47', 'sensor_48', 'sensor_49', 'sensor_50', 'sensor_51', 'machine_status']
2026-04-20 14:45:09,212 | INFO | capstone.file_io | Resolved dataset name during Bronze ingest | dataset_name=pump | source_column=config | method=config
2026-04-20 14:45:09,571 | INFO | capstone.bronze | Shape: (220320, 63)
2026-04-20 14:45:09,578 | INFO | capstone.bronze | Dtypes:
meta__dataset                       category
meta__split                         category
meta__run_id                          object
meta__asset_id                        object
meta__ingested_at_utc    datetime64[us, UTC]
meta__source_file             string[python]
meta__source_row_id                    int64
meta__record_id                       uint64
Unnamed: 0                             int64
timestamp                             object
sensor_00                            float64
sensor_01                            float64
sensor_02                            float64
sensor_03                            float64
sensor_04                            float64
sensor_05                            float64
sensor_06                            float64
sensor_07                            float64
sensor_08                            float64
sensor_09                            float64
sensor_10                            float64
sensor_11                            float64
sensor_12                            float64
sensor_13                            float64
sensor_14                            float64
sensor_15                            float64
sensor_16                            float64
sensor_17                            float64
sensor_18                            float64
sensor_19                            float64
sensor_20                            float64
sensor_21                            float64
sensor_22                            float64
sensor_23                            float64
sensor_24                            float64
sensor_25                            float64
sensor_26                            float64
sensor_27                            float64
sensor_28                            float64
sensor_29                            float64
sensor_30                            float64
sensor_31                            float64
sensor_32                            float64
sensor_33                            float64
sensor_34                            float64
sensor_35                            float64
sensor_36                            float64
sensor_37                            float64
sensor_38                            float64
sensor_39                            float64
sensor_40                            float64
sensor_41                            float64
sensor_42                            float64
sensor_43                            float64
sensor_44                            float64
sensor_45                            float64
sensor_46                            float64
sensor_47                            float64
sensor_48                            float64
sensor_49                            float64
sensor_50                            float64
sensor_51                            float64
machine_status                        object

Shape: (220320, 63)

Data types:
meta__dataset                       category
meta__split                         category
meta__run_id                          object
meta__asset_id                        object
meta__ingested_at_utc    datetime64[us, UTC]
                                ...
sensor_48                            float64
sensor_49                            float64
sensor_50                            float64
sensor_51                            float64
machine_status                        object
Length: 63, dtype: object

Memory usage (MB):

2026-04-20 14:45:09,994 | INFO | capstone.bronze | Memory usage (MB): 165.63

165.62513065338135

First 15 rows:

,meta__dataset,meta__split,meta__run_id,meta__asset_id,meta__ingested_at_utc,meta__source_file,meta__source_row_id,meta__record_id,Unnamed: 0,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,sensor_09,sensor_10,sensor_11,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,sensor_22,sensor_23,sensor_24,sensor_25,sensor_26,sensor_27,sensor_28,sensor_29,sensor_30,sensor_31,sensor_32,sensor_33,sensor_34,sensor_35,sensor_36,sensor_37,sensor_38,sensor_39,sensor_40,sensor_41,sensor_42,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
0,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,0,14598431322315673869,0,2018-04-01 00:00:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,15.05353,37.22740,47.52422,31.11716,1.681353,419.5747,NaN,461.8781,466.3284,2.565284,665.3993,398.9862,880.0001,498.8926,975.9409,627.6740,741.7151,848.0708,429.0377,785.1935,684.9443,594.4445,682.8125,680.4416,433.7037,171.9375,341.9039,195.0655,90.32386,40.36458,31.51042,70.57291,30.989580,31.770832,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,1,15954729095895098000,1,2018-04-01 00:01:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,15.05353,37.22740,47.52422,31.11716,1.681353,419.5747,NaN,461.8781,466.3284,2.565284,665.3993,398.9862,880.0001,498.8926,975.9409,627.6740,741.7151,848.0708,429.0377,785.1935,684.9443,594.4445,682.8125,680.4416,433.7037,171.9375,341.9039,195.0655,90.32386,40.36458,31.51042,70.57291,30.989580,31.770832,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,2,10041703297090838359,2,2018-04-01 00:02:00,2.444734,47.35243,53.2118,46.397570,638.8889,73.54598,13.32465,16.03733,15.61777,15.01013,37.86777,48.17723,32.08894,1.708474,420.8480,NaN,462.7798,459.6364,2.500062,666.2234,399.9418,880.4237,501.3617,982.7342,631.1326,740.8031,849.8997,454.2390,778.5734,715.6266,661.5740,721.8750,694.7721,441.2635,169.9820,343.1955,200.9694,93.90508,41.40625,31.25000,69.53125,30.468750,31.770830,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL
3,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,3,2072036352569063261,3,2018-04-01 00:03:00,2.460474,47.09201,53.1684,46.397568,628.1250,76.98898,13.31742,16.24711,15.69734,15.08247,38.57977,48.65607,31.67221,1.579427,420.7494,NaN,462.8980,460.8858,2.509521,666.0114,399.1046,878.8917,499.0430,977.7520,625.4076,739.2722,847.7579,474.8731,779.5091,690.4011,686.1111,754.6875,683.3831,446.2493,166.4987,343.9586,193.1689,101.04060,41.92708,31.51042,72.13541,30.468750,31.510420,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL
4,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,4,4365040424004714369,4,2018-04-01 00:04:00,2.445718,47.13541,53.2118,46.397568,636.4583,76.58897,13.35359,16.21094,15.69734,15.08247,39.48939,49.06298,31.95202,1.683831,419.8926,NaN,461.4906,468.2206,2.604785,663.2111,400.5426,882.5874,498.5383,979.5755,627.1830,737.6033,846.9182,408.8159,785.2307,704.6937,631.4814,766.1458,702.4431,433.9081,164.7498,339.9630,193.8770,101.70380,42.70833,31.51042,76.82291,30.989580,31.510420,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL
5,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,5,13731207034657248969,5,2018-04-01 00:05:00,2.453588,47.09201,53.1684,46.397568,637.6157,78.18568,13.41146,16.16753,15.89265,15.16204,39.29406,49.37051,32.23816,1.673484,418.9049,NaN,461.8948,461.9289,2.507935,663.4962,398.6428,872.4973,498.4064,974.6847,624.3462,739.2036,846.4617,429.6945,777.2820,700.7193,623.1481,734.3750,711.2128,438.6517,162.8758,333.7975,196.4579,90.84048,42.70833,31.77083,79.94791,30.989580,31.250000,42.70833,38.773150,63.65741,51.79398,38.773150,164.6412,66.55093,241.6088,201.6782,NORMAL
6,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,6,7206199315957152377,6,2018-04-01 00:06:00,2.455556,47.04861,53.1684,46.397568,633.3333,75.81614,13.43316,16.13136,15.65393,15.08247,38.29974,49.57146,32.00982,1.684984,420.3324,NaN,464.2402,467.5146,2.598702,667.4751,401.1847,882.7164,500.4944,981.2908,631.2756,740.9517,853.9647,458.3623,771.8188,722.5254,674.0740,707.8125,716.1951,433.5065,161.9678,330.3747,194.0652,89.23161,42.70833,32.29166,79.94791,31.250000,31.510420,43.22916,38.194440,61.92130,51.79398,39.062500,171.8750,67.70834,240.1620,200.2315,NORMAL
7,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,7,11632940467161475457,7,2018-04-01 00:07:00,2.449653,47.13541,53.1684,46.397568,630.6713,75.77331,13.25231,16.12413,16.19647,15.08247,37.33960,49.32732,31.88320,1.646842,417.5520,NaN,462.4563,463.8936,2.533115,662.9967,395.2946,864.6103,496.4218,966.2091,618.3017,741.4593,834.6233,476.1262,784.8675,703.1723,653.2407,768.7500,723.7064,451.6564,162.8504,327.9788,196.9991,87.68256,42.96875,32.55208,78.38541,30.989580,31.510416,42.96875,38.194443,59.60648,50.92593,39.351850,178.5301,68.57639,241.3194,201.0995,NORMAL
8,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,8,4003627476009805685,8,2018-04-01 00:08:00,2.463426,47.09201,53.1684,46.397568,631.9444,74.58916,13.28848,16.13136,15.47309,15.11863,38.45401,50.28795,32.09234,1.686156,422.0777,NaN,463.4988,461.5460,2.526590,666.7677,400.1693,881.6849,500.8832,982.4542,629.5605,743.5971,852.8547,480.1708,791.9694,716.4828,666.6666,718.2291,671.4195,439.8698,155.7845,316.8784,197.1554,89.55923,42.70833,32.55208,75.52083,30.989582,31.510416,42.18750,38.194440,57.87037,50.63657,39.351850,182.0023,69.44444,243.0556,201.6782,NORMAL
9,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,9,12843418223340544546,9,2018-04-01 00:09:00,2.445718,47.17882,53.1684,46.397568,641.7823,74.57428,13.38252,16.24711,15.61777,15.11863,39.52119,50.44635,32.25679,1.637774,421.4344,NaN,463.4123,468.8477,2.630246,666.2795,400.2100,881.1141,501.1399,980.8168,629.5303,746.6206,854.3070,438.7823,799.5127,717.6339,635.1852,736.4583,699.0274,445.2378,153.0564,313.2721,195.0570,98.83604,42.70833,32.55208,73.43750,30.989582,31.510416,41.66666,39.062500,56.42361,50.63657,39.062500,186.6319,69.73380,246.5278,200.8102,NORMAL
10,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,10,12764708609319381380,10,2018-04-01 00:10:00,2.464410,47.48264,53.1250,46.397568,637.7314,76.05148,13.41146,16.16753,15.65393,15.11863,39.90199,50.48941,32.80076,1.678884,419.3340,NaN,462.5085,464.5157,2.575479,661.1370,398.3386,875.1385,497.4714,971.9780,623.6445,746.0667,845.2891,447.1741,771.0511,706.3684,667.5926,751.0416,694.1971,460.4902,154.8265,320.0443,192.2992,89.76776,42.70833,32.55208,75.52083,30.989580,31.510416,41.40625,39.351850,54.97685,50.92593,39.351850,190.9722,71.18056,250.8681,199.9421,NORMAL
11,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,11,17692035958682023704,11,2018-04-01 00:11:00,2.444734,47.91666,53.1684,46.397568,635.6482,74.58654,13.41146,16.16753,15.84925,15.11863,39.78521,50.78820,33.14559,1.625820,420.2469,NaN,464.1270,460.3733,2.506268,668.0244,399.2312,884.1331,499.8885,977.2217,626.2581,741.4160,849.9813,468.0374,783.4221,702.0211,690.7407,734.3750,711.9642,455.9620,159.5647,322.6265,192.3656,94.38536,42.96875,32.29166,78.12500,30.468750,31.510416,41.66666,39.351852,53.81944,51.21528,39.062500,193.5764,72.33796,253.1829,200.2315,NORMAL
12,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,12,9921446699215930665,12,2018-04-01 00:12:00,2.460474,48.26389,53.1250,46.397568,630.0926,76.95988,13.34635,16.16753,15.73351,15.01013,40.04284,50.50479,33.46326,1.641763,420.9848,NaN,462.6014,461.4166,2.516371,664.4367,398.4925,879.9375,498.6404,976.5900,628.4428,741.4614,850.1902,431.9778,776.2039,692.2758,618.9814,743.2291,700.5829,453.1859,161.3954,326.8734,190.6639,95.85509,42.18750,31.77083,78.64583,30.468748,31.510416,42.70833,39.351850,53.24074,50.92593,39.062500,195.6019,72.33796,253.1829,202.2569,NORMAL
13,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,13,9345101619896030940,13,2018-04-01 00:13:00,2.448669,48.43750,53.1684,46.397568,638.6574,75.67310,13.31742,16.16753,15.84925,15.16927,40.90296,50.96519,33.63691,1.675780,417.9775,NaN,463.6844,460.0434,2.523123,665.9962,399.0106,880.2982,500.0595,980.7809,628.2305,739.1381,849.8613,456.0164,773.8209,713.6832,613.4259,820.3124,689.9525,461.3610,163.0176,329.4678,193.9231,85.18916,42.70833,30.98958,77.08333,30.468748,31.510416,42.70833,40.509260,53.81944,50.63657,39.062500,196.4699,72.91666,252.8935,202.8356,NORMAL
14,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,14,12574828447392710356,14,2018-04-01 00:14:00,2.453588,48.56771,53.1684,46.397568,632.4074,80.65949,13.38976,16.13136,15.53096,15.08970,41.82584,51.72565,34.46501,1.620947,419.8773,NaN,460.1368,469.4464,2.619585,664.4193,399.8578,879.2635,498.6386,978.3185,623.9886,739.1832,846.6416,455.4812,782.1506,691.5473,637.0370,788.5416,688.3723,454.1698,165.0171,332.3613,198.3440,81.58781,44.01041,30.46875,74.47916,30.468750,31.510416,42.18750,41.666670,53.53009,50.34722,39.062500,205.4398,72.91666,252.0255,201.0995,NORMAL

2026-04-20 14:45:10,114 | INFO | capstone.bronze | Head(15):
   meta__dataset meta__split meta__run_id meta__asset_id            meta__ingested_at_utc meta__source_file  meta__source_row_id       meta__record_id  Unnamed: 0            timestamp  sensor_00  sensor_01  sensor_02  sensor_03  sensor_04  sensor_05  sensor_06  sensor_07  sensor_08  sensor_09  ...  sensor_33  sensor_34  sensor_35  sensor_36  sensor_37  sensor_38  sensor_39  sensor_40  sensor_41  sensor_42  sensor_43  sensor_44  sensor_45  sensor_46  sensor_47  sensor_48  sensor_49  sensor_50  sensor_51  machine_status
0           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    0  14598431322315673869           0  2018-04-01 00:00:00   2.465394   47.09201    53.2118  46.310760   634.3750   76.45975   13.41146   16.13136   15.56713   15.05353  ...   433.7037   171.9375   341.9039   195.0655   90.32386   40.36458   31.51042   70.57291  30.989580  31.770832   41.92708  39.641200   65.68287   50.92593  38.194440   157.9861   67.70834   243.0556   201.3889          NORMAL
1           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    1  15954729095895098000           1  2018-04-01 00:01:00   2.465394   47.09201    53.2118  46.310760   634.3750   76.45975   13.41146   16.13136   15.56713   15.05353  ...   433.7037   171.9375   341.9039   195.0655   90.32386   40.36458   31.51042   70.57291  30.989580  31.770832   41.92708  39.641200   65.68287   50.92593  38.194440   157.9861   67.70834   243.0556   201.3889          NORMAL
2           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    2  10041703297090838359           2  2018-04-01 00:02:00   2.444734   47.35243    53.2118  46.397570   638.8889   73.54598   13.32465   16.03733   15.61777   15.01013  ...   441.2635   169.9820   343.1955   200.9694   93.90508   41.40625   31.25000   69.53125  30.468750  31.770830   41.66666  39.351852   65.39352   51.21528  38.194443   155.9606   67.12963   241.3194   203.7037          NORMAL
3           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    3   2072036352569063261           3  2018-04-01 00:03:00   2.460474   47.09201    53.1684  46.397568   628.1250   76.98898   13.31742   16.24711   15.69734   15.08247  ...   446.2493   166.4987   343.9586   193.1689  101.04060   41.92708   31.51042   72.13541  30.468750  31.510420   40.88541  39.062500   64.81481   51.21528  38.194440   155.9606   66.84028   240.4514   203.1250          NORMAL
4           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    4   4365040424004714369           4  2018-04-01 00:04:00   2.445718   47.13541    53.2118  46.397568   636.4583   76.58897   13.35359   16.21094   15.69734   15.08247  ...   433.9081   164.7498   339.9630   193.8770  101.70380   42.70833   31.51042   76.82291  30.989580  31.510420   41.40625  38.773150   65.10416   51.79398  38.773150   158.2755   66.55093   242.1875   201.3889          NORMAL
5           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    5  13731207034657248969           5  2018-04-01 00:05:00   2.453588   47.09201    53.1684  46.397568   637.6157   78.18568   13.41146   16.16753   15.89265   15.16204  ...   438.6517   162.8758   333.7975   196.4579   90.84048   42.70833   31.77083   79.94791  30.989580  31.250000   42.70833  38.773150   63.65741   51.79398  38.773150   164.6412   66.55093   241.6088   201.6782          NORMAL
6           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    6   7206199315957152377           6  2018-04-01 00:06:00   2.455556   47.04861    53.1684  46.397568   633.3333   75.81614   13.43316   16.13136   15.65393   15.08247  ...   433.5065   161.9678   330.3747   194.0652   89.23161   42.70833   32.29166   79.94791  31.250000  31.510420   43.22916  38.194440   61.92130   51.79398  39.062500   171.8750   67.70834   240.1620   200.2315          NORMAL
7           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    7  11632940467161475457           7  2018-04-01 00:07:00   2.449653   47.13541    53.1684  46.397568   630.6713   75.77331   13.25231   16.12413   16.19647   15.08247  ...   451.6564   162.8504   327.9788   196.9991   87.68256   42.96875   32.55208   78.38541  30.989580  31.510416   42.96875  38.194443   59.60648   50.92593  39.351850   178.5301   68.57639   241.3194   201.0995          NORMAL
8           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    8   4003627476009805685           8  2018-04-01 00:08:00   2.463426   47.09201    53.1684  46.397568   631.9444   74.58916   13.28848   16.13136   15.47309   15.11863  ...   439.8698   155.7845   316.8784   197.1554   89.55923   42.70833   32.55208   75.52083  30.989582  31.510416   42.18750  38.194440   57.87037   50.63657  39.351850   182.0023   69.44444   243.0556   201.6782          NORMAL
9           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    9  12843418223340544546           9  2018-04-01 00:09:00   2.445718   47.17882    53.1684  46.397568   641.7823   74.57428   13.38252   16.24711   15.61777   15.11863  ...   445.2378   153.0564   313.2721   195.0570   98.83604   42.70833   32.55208   73.43750  30.989582  31.510416   41.66666  39.062500   56.42361   50.63657  39.062500   186.6319   69.73380   246.5278   200.8102          NORMAL
10          pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                   10  12764708609319381380          10  2018-04-01 00:10:00   2.464410   47.48264    53.1250  46.397568   637.7314   76.05148   13.41146   16.16753   15.65393   15.11863  ...   460.4902   154.8265   320.0443   192.2992   89.76776   42.70833   32.55208   75.52083  30.989580  31.510416   41.40625  39.351850   54.97685   50.92593  39.351850   190.9722   71.18056   250.8681   199.9421          NORMAL
11          pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                   11  17692035958682023704          11  2018-04-01 00:11:00   2.444734   47.91666    53.1684  46.397568   635.6482   74.58654   13.41146   16.16753   15.84925   15.11863  ...   455.9620   159.5647   322.6265   192.3656   94.38536   42.96875   32.29166   78.12500  30.468750  31.510416   41.66666  39.351852   53.81944   51.21528  39.062500   193.5764   72.33796   253.1829   200.2315          NORMAL
12          pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                   12   9921446699215930665          12  2018-04-01 00:12:00   2.460474   48.26389    53.1250  46.397568   630.0926   76.95988   13.34635   16.16753   15.73351   15.01013  ...   453.1859   161.3954   326.8734   190.6639   95.85509   42.18750   31.77083   78.64583  30.468748  31.510416   42.70833  39.351850   53.24074   50.92593  39.062500   195.6019   72.33796   253.1829   202.2569          NORMAL
13          pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                   13   9345101619896030940          13  2018-04-01 00:13:00   2.448669   48.43750    53.1684  46.397568   638.6574   75.67310   13.31742   16.16753   15.84925   15.16927  ...   461.3610   163.0176   329.4678   193.9231   85.18916   42.70833   30.98958   77.08333  30.468748  31.510416   42.70833  40.509260   53.81944   50.63657  39.062500   196.4699   72.91666   252.8935   202.8356          NORMAL
14          pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                   14  12574828447392710356          14  2018-04-01 00:14:00   2.453588   48.56771    53.1684  46.397568   632.4074   80.65949   13.38976   16.13136   15.53096   15.08970  ...   454.1698   165.0171   332.3613   198.3440   81.58781   44.01041   30.46875   74.47916  30.468750  31.510416   42.18750  41.666670   53.53009   50.34722  39.062500   205.4398   72.91666   252.0255   201.0995          NORMAL

Basic numeric summary:

                        count          mean           std           min           25%           50%           75%           max
meta__source_row_id  220320.0  1.101595e+05  6.360105e+04  0.000000e+00  5.507975e+04  1.101595e+05  1.652392e+05  2.203190e+05
meta__record_id      220320.0  9.224243e+18  5.322367e+18  1.873763e+14  4.610703e+18  9.220552e+18  1.381850e+19  1.844674e+19
Unnamed: 0           220320.0  1.101595e+05  6.360105e+04  0.000000e+00  5.507975e+04  1.101595e+05  1.652392e+05  2.203190e+05
sensor_00            210112.0  2.372221e+00  4.122274e-01  0.000000e+00  2.438831e+00  2.456539e+00  2.499826e+00  2.549016e+00
sensor_01            219951.0  4.759161e+01  3.296666e+00  0.000000e+00  4.631076e+01  4.813368e+01  4.947916e+01  5.672743e+01
sensor_02            220301.0  5.086739e+01  3.666820e+00  3.315972e+01  5.039062e+01  5.164930e+01  5.277777e+01  5.603299e+01
sensor_03            220301.0  4.375248e+01  2.418887e+00  3.164062e+01  4.283854e+01  4.422743e+01  4.531250e+01  4.822049e+01
sensor_04            220301.0  5.906739e+02  1.440239e+02  2.798032e+00  6.266204e+02  6.326389e+02  6.376157e+02  8.000000e+02
sensor_05            220301.0  7.339641e+01  1.729825e+01  0.000000e+00  6.997626e+01  7.557679e+01  8.091215e+01  9.999988e+01
sensor_06            215522.0  1.350154e+01  2.163736e+00  1.446759e-02  1.334635e+01  1.364294e+01  1.453993e+01  2.225116e+01
sensor_07            214869.0  1.584315e+01  2.201155e+00  0.000000e+00  1.590712e+01  1.616753e+01  1.642795e+01  2.359664e+01
sensor_08            215213.0  1.520072e+01  2.037390e+00  2.893518e-02  1.518374e+01  1.549479e+01  1.569734e+01  2.434896e+01
sensor_09            215725.0  1.479921e+01  2.091963e+00  0.000000e+00  1.505353e+01  1.508247e+01  1.511863e+01  2.500000e+01
sensor_10            220301.0  4.147034e+01  1.209352e+01  0.000000e+00  4.070526e+01  4.429134e+01  4.746376e+01  7.610686e+01
sensor_11            220301.0  4.191832e+01  1.305643e+01  0.000000e+00  3.885642e+01  4.536314e+01  4.965654e+01  6.000000e+01
sensor_12            220301.0  2.913697e+01  1.011394e+01  0.000000e+00  2.868681e+01  3.251583e+01  3.493973e+01  4.500000e+01
sensor_13            220301.0  7.078858e+00  6.901755e+00  0.000000e+00  1.538516e+00  2.929809e+00  1.285952e+01  3.118755e+01
sensor_14            220299.0  3.768600e+02  1.132064e+02  3.240955e+01  4.181033e+02  4.201062e+02  4.209971e+02  5.000000e+02
sensor_15                 0.0           NaN           NaN           NaN           NaN           NaN           NaN           NaN
sensor_16            220289.0  4.164729e+02  1.260726e+02  0.000000e+00  4.594534e+02  4.628561e+02  4.643027e+02  7.397415e+02
sensor_17            220274.0  4.211275e+02  1.291562e+02  0.000000e+00  4.541388e+02  4.620203e+02  4.668571e+02  5.999999e+02
sensor_18            220274.0  2.303785e+00  7.658831e-01  0.000000e+00  2.447542e+00  2.533704e+00  2.587682e+00  4.873250e+00
sensor_19            220304.0  5.908298e+02  1.993458e+02  0.000000e+00  6.627690e+02  6.656724e+02  6.671467e+02  8.789179e+02
sensor_20            220304.0  3.608052e+02  1.019741e+02  0.000000e+00  3.980215e+02  3.993670e+02  4.000884e+02  4.489079e+02
sensor_21            220304.0  7.962259e+02  2.266793e+02  9.552766e+01  8.754644e+02  8.796976e+02  8.821299e+02  1.107526e+03
sensor_22            220279.0  4.597928e+02  1.545283e+02  0.000000e+00  4.789626e+02  5.318559e+02  5.342549e+02  5.940611e+02
sensor_23            220304.0  9.226093e+02  2.918353e+02  0.000000e+00  9.509224e+02  9.819250e+02  1.090808e+03  1.227564e+03
sensor_24            220304.0  5.562354e+02  1.822980e+02  0.000000e+00  6.011511e+02  6.258735e+02  6.286077e+02  1.000000e+03
sensor_25            220284.0  6.491448e+02  2.208652e+02  0.000000e+00  6.939578e+02  7.402035e+02  7.503571e+02  8.395750e+02
sensor_26            220300.0  7.864118e+02  2.466636e+02  4.315479e+01  7.904896e+02  8.618696e+02  9.191048e+02  1.214420e+03
sensor_27            220304.0  5.015066e+02  1.698232e+02  0.000000e+00  4.482980e+02  4.944684e+02  5.362745e+02  2.000000e+03
sensor_28            220304.0  8.516903e+02  3.130740e+02  4.319347e+00  7.826826e+02  9.672799e+02  1.043977e+03  1.841146e+03
sensor_29            220248.0  5.761953e+02  2.257641e+02  6.365742e-01  5.189472e+02  5.648725e+02  7.440215e+02  1.466281e+03
sensor_30            220059.0  6.145964e+02  1.957269e+02  0.000000e+00  6.277778e+02  6.689814e+02  6.972222e+02  1.600000e+03
sensor_31            220304.0  8.633231e+02  2.835448e+02  2.395833e+01  8.390624e+02  9.177083e+02  9.812499e+02  1.800000e+03
sensor_32            220252.0  8.042839e+02  2.606024e+02  2.407161e-01  7.606075e+02  8.788508e+02  9.438776e+02  1.839211e+03
sensor_33            220304.0  4.864060e+02  1.507518e+02  6.460602e+00  4.897611e+02  5.122717e+02  5.551632e+02  1.578600e+03
sensor_34            220304.0  2.349718e+02  8.837606e+01  5.488237e+01  1.724863e+02  2.263560e+02  3.168449e+02  4.255498e+02
sensor_35            220304.0  4.271298e+02  1.417725e+02  0.000000e+00  3.531766e+02  4.733493e+02  5.288910e+02  6.944791e+02
sensor_36            220304.0  5.930339e+02  2.893855e+02  2.260970e+00  2.885476e+02  7.096680e+02  8.373330e+02  9.840607e+02
sensor_37            220304.0  6.078736e+01  3.760488e+01  0.000000e+00  2.879922e+01  6.429548e+01  9.082193e+01  1.749012e+02
sensor_38            220293.0  4.965595e+01  1.054040e+01  2.447917e+01  4.557291e+01  4.947916e+01  5.364583e+01  4.177083e+02
sensor_39            220293.0  3.661044e+01  1.561372e+01  1.927083e+01  3.255208e+01  3.541666e+01  3.906250e+01  5.479166e+02
sensor_40            220293.0  6.884453e+01  2.137114e+01  2.343750e+01  5.781250e+01  6.640625e+01  7.786458e+01  5.127604e+02
sensor_41            220293.0  3.536513e+01  7.898665e+00  2.083333e+01  3.255208e+01  3.489583e+01  3.776041e+01  4.203125e+02
sensor_42            220293.0  3.545346e+01  1.025952e+01  2.213542e+01  3.281250e+01  3.515625e+01  3.697916e+01  3.742188e+02
sensor_43            220293.0  4.387959e+01  1.104440e+01  2.447917e+01  3.958333e+01  4.296875e+01  4.661458e+01  4.085937e+02
sensor_44            220293.0  4.265688e+01  1.157636e+01  2.575232e+01  3.674768e+01  4.050926e+01  4.513889e+01  1.000000e+03
sensor_45            220293.0  4.309498e+01  1.283752e+01  2.633102e+01  3.674768e+01  4.021991e+01  4.484954e+01  3.203125e+02
sensor_46            220293.0  4.801859e+01  1.564128e+01  2.633102e+01  4.050926e+01  4.484954e+01  5.121528e+01  3.703704e+02
sensor_47            220293.0  4.434090e+01  1.044244e+01  2.719907e+01  3.906250e+01  4.253472e+01  4.658565e+01  3.035301e+02
sensor_48            220293.0  1.508890e+02  8.224496e+01  2.633102e+01  8.391203e+01  1.380208e+02  2.083333e+02  5.616320e+02
sensor_49            220293.0  5.711997e+01  1.914360e+01  2.662037e+01  4.774306e+01  5.266204e+01  6.076389e+01  4.644097e+02
sensor_50            143303.0  1.830493e+02  6.525865e+01  2.748843e+01  1.675347e+02  1.938657e+02  2.199074e+02  1.000000e+03
sensor_51            204937.0  2.026997e+02  1.095886e+02  2.777778e+01  1.791088e+02  1.973380e+02  2.167245e+02  1.000000e+03

2026-04-20 14:45:11,440 | INFO | capstone.bronze | Numeric describe (truncated):
                        count          mean           std           min           25%           50%           75%           max
meta__source_row_id  220320.0  1.101595e+05  6.360105e+04  0.000000e+00  5.507975e+04  1.101595e+05  1.652392e+05  2.203190e+05
meta__record_id      220320.0  9.224243e+18  5.322367e+18  1.873763e+14  4.610703e+18  9.220552e+18  1.381850e+19  1.844674e+19
Unnamed: 0           220320.0  1.101595e+05  6.360105e+04  0.000000e+00  5.507975e+04  1.101595e+05  1.652392e+05  2.203190e+05
sensor_00            210112.0  2.372221e+00  4.122274e-01  0.000000e+00  2.438831e+00  2.456539e+00  2.499826e+00  2.549016e+00
sensor_01            219951.0  4.759161e+01  3.296666e+00  0.000000e+00  4.631076e+01  4.813368e+01  4.947916e+01  5.672743e+01
sensor_02            220301.0  5.086739e+01  3.666820e+00  3.315972e+01  5.039062e+01  5.164930e+01  5.277777e+01  5.603299e+01
sensor_03            220301.0  4.375248e+01  2.418887e+00  3.164062e+01  4.283854e+01  4.422743e+01  4.531250e+01  4.822049e+01
sensor_04            220301.0  5.906739e+02  1.440239e+02  2.798032e+00  6.266204e+02  6.326389e+02  6.376157e+02  8.000000e+02
sensor_05            220301.0  7.339641e+01  1.729825e+01  0.000000e+00  6.997626e+01  7.557679e+01  8.091215e+01  9.999988e+01
sensor_06            215522.0  1.350154e+01  2.163736e+00  1.446759e-02  1.334635e+01  1.364294e+01  1.453993e+01  2.225116e+01
sensor_07            214869.0  1.584315e+01  2.201155e+00  0.000000e+00  1.590712e+01  1.616753e+01  1.642795e+01  2.359664e+01
sensor_08            215213.0  1.520072e+01  2.037390e+00  2.893518e-02  1.518374e+01  1.549479e+01  1.569734e+01  2.434896e+01
sensor_09            215725.0  1.479921e+01  2.091963e+00  0.000000e+00  1.505353e+01  1.508247e+01  1.511863e+01  2.500000e+01
sensor_10            220301.0  4.147034e+01  1.209352e+01  0.000000e+00  4.070526e+01  4.429134e+01  4.746376e+01  7.610686e+01
sensor_11            220301.0  4.191832e+01  1.305643e+01  0.000000e+00  3.885642e+01  4.536314e+01  4.965654e+01  6.000000e+01
sensor_12            220301.0  2.913697e+01  1.011394e+01  0.000000e+00  2.868681e+01  3.251583e+01  3.493973e+01  4.500000e+01
sensor_13            220301.0  7.078858e+00  6.901755e+00  0.000000e+00  1.538516e+00  2.929809e+00  1.285952e+01  3.118755e+01
sensor_14            220299.0  3.768600e+02  1.132064e+02  3.240955e+01  4.181033e+02  4.201062e+02  4.209971e+02  5.000000e+02
sensor_15                 0.0           NaN           NaN           NaN           NaN           NaN           NaN           NaN
sensor_16            220289.0  4.164729e+02  1.260726e+02  0.000000e+00  4.594534e+02  4.628561e+02  4.643027e+02  7.397415e+02
sensor_17            220274.0  4.211275e+02  1.291562e+02  0.000000e+00  4.541388e+02  4.620203e+02  4.668571e+02  5.999999e+02
sensor_18            220274.0  2.303785e+00  7.658831e-01  0.000000e+00  2.447542e+00  2.533704e+00  2.587682e+00  4.873250e+00
sensor_19            220304.0  5.908298e+02  1.993458e+02  0.000000e+00  6.627690e+02  6.656724e+02  6.671467e+02  8.789179e+02
sensor_20            220304.0  3.608052e+02  1.019741e+02  0.000000e+00  3.980215e+02  3.993670e+02  4.000884e+02  4.489079e+02
sensor_21            220304.0  7.962259e+02  2.266793e+02  9.552766e+01  8.754644e+02  8.796976e+02  8.821299e+02  1.107526e+03
sensor_22            220279.0  4.597928e+02  1.545283e+02  0.000000e+00  4.789626e+02  5.318559e+02  5.342549e+02  5.940611e+02
sensor_23            220304.0  9.226093e+02  2.918353e+02  0.000000e+00  9.509224e+02  9.819250e+02  1.090808e+03  1.227564e+03
sensor_24            220304.0  5.562354e+02  1.822980e+02  0.000000e+00  6.011511e+02  6.258735e+02  6.286077e+02  1.000000e+03
sensor_25            220284.0  6.491448e+02  2.208652e+02  0.000000e+00  6.939578e+02  7.402035e+02  7.503571e+02  8.395750e+02
sensor_26            220300.0  7.864118e+02  2.466636e+02  4.315479e+01  7.904896e+02  8.618696e+02  9.191048e+02  1.214420e+03
sensor_27            220304.0  5.015066e+02  1.698232e+02  0.000000e+00  4.482980e+02  4.944684e+02  5.362745e+02  2.000000e+03
sensor_28            220304.0  8.516903e+02  3.130740e+02  4.319347e+00  7.826826e+02  9.672799e+02  1.043977e+03  1.841146e+03
sensor_29            220248.0  5.761953e+02  2.257641e+02  6.365742e-01  5.189472e+02  5.648725e+02  7.440215e+02  1.466281e+03
sensor_30            220059.0  6.145964e+02  1.957269e+02  0.000000e+00  6.277778e+02  6.689814e+02  6.972222e+02  1.600000e+03
sensor_31            220304.0  8.633231e+02  2.835448e+02  2.395833e+01  8.390624e+02  9.177083e+02  9.812499e+02  1.800000e+03
sensor_32            220252.0  8.042839e+02  2.606024e+02  2.407161e-01  7.606075e+02  8.788508e+02  9.438776e+02  1.839211e+03
sensor_33            220304.0  4.864060e+02  1.507518e+02  6.460602e+00  4.897611e+02  5.122717e+02  5.551632e+02  1.578600e+03
sensor_34            220304.0  2.349718e+02  8.837606e+01  5.488237e+01  1.724863e+02  2.263560e+02  3.168449e+02  4.255498e+02
sensor_35            220304.0  4.271298e+02  1.417725e+02  0.000000e+00  3.531766e+02  4.733493e+02  5.288910e+02  6.944791e+02
sensor_36            220304.0  5.930339e+02  2.893855e+02  2.260970e+00  2.885476e+02  7.096680e+02  8.373330e+02  9.840607e+02
sensor_37            220304.0  6.078736e+01  3.760488e+01  0.000000e+00  2.879922e+01  6.429548e+01  9.082193e+01  1.749012e+02
sensor_38            220293.0  4.965595e+01  1.054040e+01  2.447917e+01  4.557291e+01  4.947916e+01  5.364583e+01  4.177083e+02
sensor_39            220293.0  3.661044e+01  1.561372e+01  1.927083e+01  3.255208e+01  3.541666e+01  3.906250e+01  5.479166e+02
sensor_40            220293.0  6.884453e+01  2.137114e+01  2.343750e+01  5.781250e+01  6.640625e+01  7.786458e+01  5.127604e+02
sensor_41            220293.0  3.536513e+01  7.898665e+00  2.083333e+01  3.255208e+01  3.489583e+01  3.776041e+01  4.203125e+02
sensor_42            220293.0  3.545346e+01  1.025952e+01  2.213542e+01  3.281250e+01  3.515625e+01  3.697916e+01  3.742188e+02
sensor_43            220293.0  4.387959e+01  1.104440e+01  2.447917e+01  3.958333e+01  4.296875e+01  4.661458e+01  4.085937e+02
sensor_44            220293.0  4.265688e+01  1.157636e+01  2.575232e+01  3.674768e+01  4.050926e+01  4.513889e+01  1.000000e+03
sensor_45            220293.0  4.309498e+01  1.283752e+01  2.633102e+01  3.674768e+01  4.021991e+01  4.484954e+01  3.203125e+02
sensor_46            220293.0  4.801859e+01  1.564128e+01  2.633102e+01  4.050926e+01  4.484954e+01  5.121528e+01  3.703704e+02
sensor_47            220293.0  4.434090e+01  1.044244e+01  2.719907e+01  3.906250e+01  4.253472e+01  4.658565e+01  3.035301e+02
sensor_48            220293.0  1.508890e+02  8.224496e+01  2.633102e+01  8.391203e+01  1.380208e+02  2.083333e+02  5.616320e+02
sensor_49            220293.0  5.711997e+01  1.914360e+01  2.662037e+01  4.774306e+01  5.266204e+01  6.076389e+01  4.644097e+02
sensor_50            143303.0  1.830493e+02  6.525865e+01  2.748843e+01  1.675347e+02  1.938657e+02  2.199074e+02  1.000000e+03
sensor_51            204937.0  2.026997e+02  1.095886e+02  2.777778e+01  1.791088e+02  1.973380e+02  2.167245e+02  1.000000e+03

Basic object / categorical summary:

                    count  unique                  top    freq
meta__dataset      220320       1                 pump  220320
meta__split        220320       1              unsplit  220320
meta__run_id       220320       1             run__001  220320
meta__asset_id     220320       1           asset__001  220320
meta__source_file  220320       1           sensor.csv  220320
timestamp          220320  220320  2018-08-31 23:43:00       1
machine_status     220320       3               NORMAL  205836

2026-04-20 14:45:11,868 | INFO | capstone.bronze | Object/categorical describe (truncated):
                    count  unique                  top    freq
meta__dataset      220320       1                 pump  220320
meta__split        220320       1              unsplit  220320
meta__run_id       220320       1             run__001  220320
meta__asset_id     220320       1           asset__001  220320
meta__source_file  220320       1           sensor.csv  220320
timestamp          220320  220320  2018-08-31 23:43:00       1
machine_status     220320       3               NORMAL  205836
2026-04-20 14:45:11,893 | INFO | capstone.bronze | Meta Columns: (8): meta__dataset
meta__split
meta__run_id
meta__asset_id
meta__ingested_at_utc
meta__source_file
meta__source_row_id
meta__record_id
2026-04-20 14:45:11,946 | INFO | capstone.bronze | All Other Columns: (55): Unnamed: 0
timestamp
sensor_00
sensor_01
sensor_02
sensor_03
sensor_04
sensor_05
sensor_06
sensor_07
sensor_08
sensor_09
sensor_10
sensor_11
sensor_12
sensor_13
sensor_14
sensor_15
sensor_16
sensor_17
sensor_18
sensor_19
sensor_20
sensor_21
sensor_22
sensor_23
sensor_24
sensor_25
sensor_26
sensor_27
sensor_28
sensor_29
sensor_30
sensor_31
sensor_32
sensor_33
sensor_34
sensor_35
sensor_36
sensor_37
sensor_38
sensor_39
sensor_40
sensor_41
sensor_42
sensor_43
sensor_44
sensor_45
sensor_46
sensor_47
sensor_48
sensor_49
sensor_50
sensor_51
machine_status

Meta Columns Summary:

All Other Columns Summary:

           pct_missing
sensor_15   100.000000
sensor_50    34.956881
sensor_51     6.982117
sensor_00     4.633261
sensor_07     2.474129
sensor_08     2.317992
sensor_06     2.177741
sensor_09     2.085603
sensor_01     0.167484
sensor_30     0.118464
sensor_29     0.032680
sensor_32     0.030864
sensor_18     0.020879
sensor_17     0.020879
sensor_22     0.018609
sensor_25     0.016340
sensor_16     0.014070
sensor_45     0.012255
sensor_39     0.012255
sensor_43     0.012255

2026-04-20 14:45:12,033 | INFO | capstone.bronze | Top missingness (%):
sensor_15    100.000000
sensor_50     34.956881
sensor_51      6.982117
sensor_00      4.633261
sensor_07      2.474129
sensor_08      2.317992
sensor_06      2.177741
sensor_09      2.085603
sensor_01      0.167484
sensor_30      0.118464
sensor_29      0.032680
sensor_32      0.030864
sensor_18      0.020879
sensor_17      0.020879
sensor_22      0.018609
sensor_25      0.016340
sensor_16      0.014070
sensor_45      0.012255
sensor_39      0.012255
sensor_43      0.012255
2026-04-20 14:45:12,150 | INFO | capstone.bronze | Bronze truth hash: 72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976
2026-04-20 14:45:12,154 | INFO | capstone.bronze | Bronze truth path: /workspace/artifacts/truths/bronze/pump__bronze__truth__72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976.json
2026-04-20 14:45:12,156 | INFO | capstone.bronze | Bronze process_run_id: bronze_process__20260420T144501Z

Bronze truth hash: 72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976
Bronze truth path: /workspace/artifacts/truths/bronze/pump__bronze__truth__72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976.json
Bronze process_run_id: bronze_process__20260420T144501Z

2026-04-20 14:45:12,372 | INFO | capstone.bronze | Bronze columns reordered successfully. Meta columns moved to the front while preserving original within-group order. meta_column_count=11 | non_meta_column_count=55 | total_column_count=66
2026-04-20 14:45:12,382 | INFO | capstone.file_io | Saving DataFrame to Parquet: /workspace/data/bronze/train/pump__bronze__train.parquet
2026-04-20 14:45:14,404 | INFO | capstone.file_io | Saved: pump__bronze__train.parquet | shape=(220320, 66) | columns=['meta__dataset', 'meta__split', 'meta__run_id', 'meta__asset_id', 'meta__ingested_at_utc', 'meta__source_file', 'meta__source_row_id', 'meta__record_id', 'meta__truth_hash', 'meta__parent_truth_hash', 'meta__pipeline_mode', 'Unnamed: 0', 'timestamp', 'sensor_00', 'sensor_01', 'sensor_02', 'sensor_03', 'sensor_04', 'sensor_05', 'sensor_06', 'sensor_07', 'sensor_08', 'sensor_09', 'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21', 'sensor_22', 'sensor_23', 'sensor_24', 'sensor_25', 'sensor_26', 'sensor_27', 'sensor_28', 'sensor_29', 'sensor_30', 'sensor_31', 'sensor_32', 'sensor_33', 'sensor_34', 'sensor_35', 'sensor_36', 'sensor_37', 'sensor_38', 'sensor_39', 'sensor_40', 'sensor_41', 'sensor_42', 'sensor_43', 'sensor_44', 'sensor_45', 'sensor_46', 'sensor_47', 'sensor_48', 'sensor_49', 'sensor_50', 'sensor_51', 'machine_status']
2026-04-20 14:45:14,733 | INFO | capstone.bronze | Shape: (220320, 66)
2026-04-20 14:45:14,735 | INFO | capstone.bronze | Memory (MB): 209.12
2026-04-20 14:45:14,739 | INFO | capstone.bronze | Dtypes:
meta__dataset                         category
meta__split                           category
meta__run_id                            object
meta__asset_id                          object
meta__ingested_at_utc      datetime64[us, UTC]
meta__source_file               string[python]
meta__source_row_id                      int64
meta__record_id                         uint64
meta__truth_hash                        object
meta__parent_truth_hash                 object
meta__pipeline_mode                     object
Unnamed: 0                               int64
timestamp                               object
sensor_00                              float64
sensor_01                              float64
sensor_02                              float64
sensor_03                              float64
sensor_04                              float64
sensor_05                              float64
sensor_06                              float64
sensor_07                              float64
sensor_08                              float64
sensor_09                              float64
sensor_10                              float64
sensor_11                              float64
sensor_12                              float64
sensor_13                              float64
sensor_14                              float64
sensor_15                              float64
sensor_16                              float64
sensor_17                              float64
sensor_18                              float64
sensor_19                              float64
sensor_20                              float64
sensor_21                              float64
sensor_22                              float64
sensor_23                              float64
sensor_24                              float64
sensor_25                              float64
sensor_26                              float64
sensor_27                              float64
sensor_28                              float64
sensor_29                              float64
sensor_30                              float64
sensor_31                              float64
sensor_32                              float64
sensor_33                              float64
sensor_34                              float64
sensor_35                              float64
sensor_36                              float64
sensor_37                              float64
sensor_38                              float64
sensor_39                              float64
sensor_40                              float64
sensor_41                              float64
sensor_42                              float64
sensor_43                              float64
sensor_44                              float64
sensor_45                              float64
sensor_46                              float64
sensor_47                              float64
sensor_48                              float64
sensor_49                              float64
sensor_50                              float64
sensor_51                              float64
machine_status                          object
2026-04-20 14:45:14,764 | INFO | capstone.bronze | Head(15):
   meta__dataset meta__split meta__run_id meta__asset_id            meta__ingested_at_utc meta__source_file  meta__source_row_id       meta__record_id                                                  meta__truth_hash meta__parent_truth_hash meta__pipeline_mode  Unnamed: 0            timestamp  sensor_00  sensor_01  sensor_02  sensor_03  sensor_04  sensor_05  sensor_06  ...  sensor_33  sensor_34  sensor_35  sensor_36  sensor_37  sensor_38  sensor_39  sensor_40  sensor_41  sensor_42  sensor_43  sensor_44  sensor_45  sensor_46  sensor_47  sensor_48  sensor_49  sensor_50  sensor_51  machine_status
0           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    0  14598431322315673869  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch           0  2018-04-01 00:00:00   2.465394   47.09201    53.2118  46.310760   634.3750   76.45975   13.41146  ...   433.7037   171.9375   341.9039   195.0655   90.32386   40.36458   31.51042   70.57291  30.989580  31.770832   41.92708  39.641200   65.68287   50.92593  38.194440   157.9861   67.70834   243.0556   201.3889          NORMAL
1           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    1  15954729095895098000  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch           1  2018-04-01 00:01:00   2.465394   47.09201    53.2118  46.310760   634.3750   76.45975   13.41146  ...   433.7037   171.9375   341.9039   195.0655   90.32386   40.36458   31.51042   70.57291  30.989580  31.770832   41.92708  39.641200   65.68287   50.92593  38.194440   157.9861   67.70834   243.0556   201.3889          NORMAL
2           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    2  10041703297090838359  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch           2  2018-04-01 00:02:00   2.444734   47.35243    53.2118  46.397570   638.8889   73.54598   13.32465  ...   441.2635   169.9820   343.1955   200.9694   93.90508   41.40625   31.25000   69.53125  30.468750  31.770830   41.66666  39.351852   65.39352   51.21528  38.194443   155.9606   67.12963   241.3194   203.7037          NORMAL
3           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    3   2072036352569063261  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch           3  2018-04-01 00:03:00   2.460474   47.09201    53.1684  46.397568   628.1250   76.98898   13.31742  ...   446.2493   166.4987   343.9586   193.1689  101.04060   41.92708   31.51042   72.13541  30.468750  31.510420   40.88541  39.062500   64.81481   51.21528  38.194440   155.9606   66.84028   240.4514   203.1250          NORMAL
4           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    4   4365040424004714369  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch           4  2018-04-01 00:04:00   2.445718   47.13541    53.2118  46.397568   636.4583   76.58897   13.35359  ...   433.9081   164.7498   339.9630   193.8770  101.70380   42.70833   31.51042   76.82291  30.989580  31.510420   41.40625  38.773150   65.10416   51.79398  38.773150   158.2755   66.55093   242.1875   201.3889          NORMAL
5           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    5  13731207034657248969  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch           5  2018-04-01 00:05:00   2.453588   47.09201    53.1684  46.397568   637.6157   78.18568   13.41146  ...   438.6517   162.8758   333.7975   196.4579   90.84048   42.70833   31.77083   79.94791  30.989580  31.250000   42.70833  38.773150   63.65741   51.79398  38.773150   164.6412   66.55093   241.6088   201.6782          NORMAL
6           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    6   7206199315957152377  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch           6  2018-04-01 00:06:00   2.455556   47.04861    53.1684  46.397568   633.3333   75.81614   13.43316  ...   433.5065   161.9678   330.3747   194.0652   89.23161   42.70833   32.29166   79.94791  31.250000  31.510420   43.22916  38.194440   61.92130   51.79398  39.062500   171.8750   67.70834   240.1620   200.2315          NORMAL
7           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    7  11632940467161475457  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch           7  2018-04-01 00:07:00   2.449653   47.13541    53.1684  46.397568   630.6713   75.77331   13.25231  ...   451.6564   162.8504   327.9788   196.9991   87.68256   42.96875   32.55208   78.38541  30.989580  31.510416   42.96875  38.194443   59.60648   50.92593  39.351850   178.5301   68.57639   241.3194   201.0995          NORMAL
8           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    8   4003627476009805685  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch           8  2018-04-01 00:08:00   2.463426   47.09201    53.1684  46.397568   631.9444   74.58916   13.28848  ...   439.8698   155.7845   316.8784   197.1554   89.55923   42.70833   32.55208   75.52083  30.989582  31.510416   42.18750  38.194440   57.87037   50.63657  39.351850   182.0023   69.44444   243.0556   201.6782          NORMAL
9           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    9  12843418223340544546  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch           9  2018-04-01 00:09:00   2.445718   47.17882    53.1684  46.397568   641.7823   74.57428   13.38252  ...   445.2378   153.0564   313.2721   195.0570   98.83604   42.70833   32.55208   73.43750  30.989582  31.510416   41.66666  39.062500   56.42361   50.63657  39.062500   186.6319   69.73380   246.5278   200.8102          NORMAL
10          pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                   10  12764708609319381380  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch          10  2018-04-01 00:10:00   2.464410   47.48264    53.1250  46.397568   637.7314   76.05148   13.41146  ...   460.4902   154.8265   320.0443   192.2992   89.76776   42.70833   32.55208   75.52083  30.989580  31.510416   41.40625  39.351850   54.97685   50.92593  39.351850   190.9722   71.18056   250.8681   199.9421          NORMAL
11          pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                   11  17692035958682023704  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch          11  2018-04-01 00:11:00   2.444734   47.91666    53.1684  46.397568   635.6482   74.58654   13.41146  ...   455.9620   159.5647   322.6265   192.3656   94.38536   42.96875   32.29166   78.12500  30.468750  31.510416   41.66666  39.351852   53.81944   51.21528  39.062500   193.5764   72.33796   253.1829   200.2315          NORMAL
12          pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                   12   9921446699215930665  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch          12  2018-04-01 00:12:00   2.460474   48.26389    53.1250  46.397568   630.0926   76.95988   13.34635  ...   453.1859   161.3954   326.8734   190.6639   95.85509   42.18750   31.77083   78.64583  30.468748  31.510416   42.70833  39.351850   53.24074   50.92593  39.062500   195.6019   72.33796   253.1829   202.2569          NORMAL
13          pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                   13   9345101619896030940  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch          13  2018-04-01 00:13:00   2.448669   48.43750    53.1684  46.397568   638.6574   75.67310   13.31742  ...   461.3610   163.0176   329.4678   193.9231   85.18916   42.70833   30.98958   77.08333  30.468748  31.510416   42.70833  40.509260   53.81944   50.63657  39.062500   196.4699   72.91666   252.8935   202.8356          NORMAL
14          pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                   14  12574828447392710356  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch          14  2018-04-01 00:14:00   2.453588   48.56771    53.1684  46.397568   632.4074   80.65949   13.38976  ...   454.1698   165.0171   332.3613   198.3440   81.58781   44.01041   30.46875   74.47916  30.468750  31.510416   42.18750  41.666670   53.53009   50.34722  39.062500   205.4398   72.91666   252.0255   201.0995          NORMAL
2026-04-20 14:45:15,975 | INFO | capstone.bronze | No boolean columns to describe; skipping.
2026-04-20 14:45:15,977 | INFO | capstone.bronze | Saved describe artifacts to: /workspace/artifacts/bronze/pump
2026-04-20 14:45:16,580 | INFO | capstone.bronze | Shape: (220320, 66)
2026-04-20 14:45:16,583 | INFO | capstone.bronze | Memory (MB): 209.12
2026-04-20 14:45:16,586 | INFO | capstone.bronze | Dtypes:
meta__dataset                         category
meta__split                           category
meta__run_id                            object
meta__asset_id                          object
meta__ingested_at_utc      datetime64[us, UTC]
meta__source_file               string[python]
meta__source_row_id                      int64
meta__record_id                         uint64
meta__truth_hash                        object
meta__parent_truth_hash                 object
meta__pipeline_mode                     object
Unnamed: 0                               int64
timestamp                               object
sensor_00                              float64
sensor_01                              float64
sensor_02                              float64
sensor_03                              float64
sensor_04                              float64
sensor_05                              float64
sensor_06                              float64
sensor_07                              float64
sensor_08                              float64
sensor_09                              float64
sensor_10                              float64
sensor_11                              float64
sensor_12                              float64
sensor_13                              float64
sensor_14                              float64
sensor_15                              float64
sensor_16                              float64
sensor_17                              float64
sensor_18                              float64
sensor_19                              float64
sensor_20                              float64
sensor_21                              float64
sensor_22                              float64
sensor_23                              float64
sensor_24                              float64
sensor_25                              float64
sensor_26                              float64
sensor_27                              float64
sensor_28                              float64
sensor_29                              float64
sensor_30                              float64
sensor_31                              float64
sensor_32                              float64
sensor_33                              float64
sensor_34                              float64
sensor_35                              float64
sensor_36                              float64
sensor_37                              float64
sensor_38                              float64
sensor_39                              float64
sensor_40                              float64
sensor_41                              float64
sensor_42                              float64
sensor_43                              float64
sensor_44                              float64
sensor_45                              float64
sensor_46                              float64
sensor_47                              float64
sensor_48                              float64
sensor_49                              float64
sensor_50                              float64
sensor_51                              float64
machine_status                          object
2026-04-20 14:45:16,612 | INFO | capstone.bronze | Head(15):
   meta__dataset meta__split meta__run_id meta__asset_id            meta__ingested_at_utc meta__source_file  meta__source_row_id       meta__record_id                                                  meta__truth_hash meta__parent_truth_hash meta__pipeline_mode  Unnamed: 0            timestamp  sensor_00  sensor_01  sensor_02  sensor_03  sensor_04  sensor_05  sensor_06  ...  sensor_33  sensor_34  sensor_35  sensor_36  sensor_37  sensor_38  sensor_39  sensor_40  sensor_41  sensor_42  sensor_43  sensor_44  sensor_45  sensor_46  sensor_47  sensor_48  sensor_49  sensor_50  sensor_51  machine_status
0           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    0  14598431322315673869  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch           0  2018-04-01 00:00:00   2.465394   47.09201    53.2118  46.310760   634.3750   76.45975   13.41146  ...   433.7037   171.9375   341.9039   195.0655   90.32386   40.36458   31.51042   70.57291  30.989580  31.770832   41.92708  39.641200   65.68287   50.92593  38.194440   157.9861   67.70834   243.0556   201.3889          NORMAL
1           pump     unsplit     run__001     asset__001 2026-04-20 14:45:09.221726+00:00        sensor.csv                    1  15954729095895098000  72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976                    None               batch           1  2018-04-01 00:01:00   2.465394   47.09201    53.2118  46.310760   634.3750   76.45975   13.41146  ...   433.7037   171.9375   341.9039   195.0655   90.32386   40.36458   31.51042   70.57291  30.989580  31.770832   41.92708  39.641200   65.68287   50.92593  38.194440   157.9861   67.70834   243.0556   201.3889          NORMAL

2026-04-20 14:45:28,056 | INFO | capstone.file_io | Loading JSON: /workspace/artifacts/truths/bronze/pump__bronze__truth__72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976.json

Bronze lineage sanity check passed.
=== Silver Pre-EDA: Data Overview ===
Shape: 220,320 rows × 66 columns

=== Column Types ===

                                       dtype
meta__dataset                       category
meta__split                         category
meta__run_id                          object
meta__asset_id                        object
meta__ingested_at_utc    datetime64[us, UTC]
meta__source_file             string[python]
meta__source_row_id                    int64
meta__record_id                       uint64
meta__truth_hash                      object
meta__parent_truth_hash               object
meta__pipeline_mode                   object
Unnamed: 0                             int64
timestamp                             object
sensor_00                            float64
sensor_01                            float64
sensor_02                            float64
sensor_03                            float64
sensor_04                            float64
sensor_05                            float64
sensor_06                            float64

=== df.info() ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220320 entries, 0 to 220319
Data columns (total 66 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   meta__dataset            220320 non-null  category
 1   meta__split              220320 non-null  category
 2   meta__run_id             220320 non-null  object
 3   meta__asset_id           220320 non-null  object
 4   meta__ingested_at_utc    220320 non-null  datetime64[us, UTC]
 5   meta__source_file        220320 non-null  string
 6   meta__source_row_id      220320 non-null  int64
 7   meta__record_id          220320 non-null  uint64
 8   meta__truth_hash         220320 non-null  object
 9   meta__parent_truth_hash  0 non-null       object
 10  meta__pipeline_mode      220320 non-null  object
 11  Unnamed: 0               220320 non-null  int64
 12  timestamp                220320 non-null  object
 13  sensor_00                210112 non-null  float64
 14  sensor_01                219951 non-null  float64
 15  sensor_02                220301 non-null  float64
 16  sensor_03                220301 non-null  float64
 17  sensor_04                220301 non-null  float64
 18  sensor_05                220301 non-null  float64
 19  sensor_06                215522 non-null  float64
 20  sensor_07                214869 non-null  float64
 21  sensor_08                215213 non-null  float64
 22  sensor_09                215725 non-null  float64
 23  sensor_10                220301 non-null  float64
 24  sensor_11                220301 non-null  float64
 25  sensor_12                220301 non-null  float64
 26  sensor_13                220301 non-null  float64
 27  sensor_14                220299 non-null  float64
 28  sensor_15                0 non-null       float64
 29  sensor_16                220289 non-null  float64
 30  sensor_17                220274 non-null  float64
 31  sensor_18                220274 non-null  float64
 32  sensor_19                220304 non-null  float64
 33  sensor_20                220304 non-null  float64
 34  sensor_21                220304 non-null  float64
 35  sensor_22                220279 non-null  float64
 36  sensor_23                220304 non-null  float64
 37  sensor_24                220304 non-null  float64
 38  sensor_25                220284 non-null  float64
 39  sensor_26                220300 non-null  float64
 40  sensor_27                220304 non-null  float64
 41  sensor_28                220304 non-null  float64
 42  sensor_29                220248 non-null  float64
 43  sensor_30                220059 non-null  float64
 44  sensor_31                220304 non-null  float64
 45  sensor_32                220252 non-null  float64
 46  sensor_33                220304 non-null  float64
 47  sensor_34                220304 non-null  float64
 48  sensor_35                220304 non-null  float64
 49  sensor_36                220304 non-null  float64
 50  sensor_37                220304 non-null  float64
 51  sensor_38                220293 non-null  float64
 52  sensor_39                220293 non-null  float64
 53  sensor_40                220293 non-null  float64
 54  sensor_41                220293 non-null  float64
 55  sensor_42                220293 non-null  float64
 56  sensor_43                220293 non-null  float64
 57  sensor_44                220293 non-null  float64
 58  sensor_45                220293 non-null  float64
 59  sensor_46                220293 non-null  float64
 60  sensor_47                220293 non-null  float64
 61  sensor_48                220293 non-null  float64
 62  sensor_49                220293 non-null  float64
 63  sensor_50                143303 non-null  float64
 64  sensor_51                204937 non-null  float64
 65  machine_status           220320 non-null  object
dtypes: category(2), datetime64[us, UTC](1), float64(52), int64(2), object(7), string(1), uint64(1)
memory usage: 108.0+ MB

=== Basic Descriptive Statistics (numeric only) ===

                        count          mean           std           min           25%           50%           75%           max
meta__source_row_id  220320.0  1.101595e+05  6.360105e+04  0.000000e+00  5.507975e+04  1.101595e+05  1.652392e+05  2.203190e+05
meta__record_id      220320.0  9.224243e+18  5.322367e+18  1.873763e+14  4.610703e+18  9.220552e+18  1.381850e+19  1.844674e+19
Unnamed: 0           220320.0  1.101595e+05  6.360105e+04  0.000000e+00  5.507975e+04  1.101595e+05  1.652392e+05  2.203190e+05
sensor_00            210112.0  2.372221e+00  4.122274e-01  0.000000e+00  2.438831e+00  2.456539e+00  2.499826e+00  2.549016e+00
sensor_01            219951.0  4.759161e+01  3.296666e+00  0.000000e+00  4.631076e+01  4.813368e+01  4.947916e+01  5.672743e+01
sensor_02            220301.0  5.086739e+01  3.666820e+00  3.315972e+01  5.039062e+01  5.164930e+01  5.277777e+01  5.603299e+01
sensor_03            220301.0  4.375248e+01  2.418887e+00  3.164062e+01  4.283854e+01  4.422743e+01  4.531250e+01  4.822049e+01
sensor_04            220301.0  5.906739e+02  1.440239e+02  2.798032e+00  6.266204e+02  6.326389e+02  6.376157e+02  8.000000e+02
sensor_05            220301.0  7.339641e+01  1.729825e+01  0.000000e+00  6.997626e+01  7.557679e+01  8.091215e+01  9.999988e+01
sensor_06            215522.0  1.350154e+01  2.163736e+00  1.446759e-02  1.334635e+01  1.364294e+01  1.453993e+01  2.225116e+01
sensor_07            214869.0  1.584315e+01  2.201155e+00  0.000000e+00  1.590712e+01  1.616753e+01  1.642795e+01  2.359664e+01
sensor_08            215213.0  1.520072e+01  2.037390e+00  2.893518e-02  1.518374e+01  1.549479e+01  1.569734e+01  2.434896e+01
sensor_09            215725.0  1.479921e+01  2.091963e+00  0.000000e+00  1.505353e+01  1.508247e+01  1.511863e+01  2.500000e+01
sensor_10            220301.0  4.147034e+01  1.209352e+01  0.000000e+00  4.070526e+01  4.429134e+01  4.746376e+01  7.610686e+01
sensor_11            220301.0  4.191832e+01  1.305643e+01  0.000000e+00  3.885642e+01  4.536314e+01  4.965654e+01  6.000000e+01
sensor_12            220301.0  2.913697e+01  1.011394e+01  0.000000e+00  2.868681e+01  3.251583e+01  3.493973e+01  4.500000e+01
sensor_13            220301.0  7.078858e+00  6.901755e+00  0.000000e+00  1.538516e+00  2.929809e+00  1.285952e+01  3.118755e+01
sensor_14            220299.0  3.768600e+02  1.132064e+02  3.240955e+01  4.181033e+02  4.201062e+02  4.209971e+02  5.000000e+02
sensor_15                 0.0           NaN           NaN           NaN           NaN           NaN           NaN           NaN
sensor_16            220289.0  4.164729e+02  1.260726e+02  0.000000e+00  4.594534e+02  4.628561e+02  4.643027e+02  7.397415e+02
sensor_17            220274.0  4.211275e+02  1.291562e+02  0.000000e+00  4.541388e+02  4.620203e+02  4.668571e+02  5.999999e+02
sensor_18            220274.0  2.303785e+00  7.658831e-01  0.000000e+00  2.447542e+00  2.533704e+00  2.587682e+00  4.873250e+00
sensor_19            220304.0  5.908298e+02  1.993458e+02  0.000000e+00  6.627690e+02  6.656724e+02  6.671467e+02  8.789179e+02
sensor_20            220304.0  3.608052e+02  1.019741e+02  0.000000e+00  3.980215e+02  3.993670e+02  4.000884e+02  4.489079e+02
sensor_21            220304.0  7.962259e+02  2.266793e+02  9.552766e+01  8.754644e+02  8.796976e+02  8.821299e+02  1.107526e+03
sensor_22            220279.0  4.597928e+02  1.545283e+02  0.000000e+00  4.789626e+02  5.318559e+02  5.342549e+02  5.940611e+02
sensor_23            220304.0  9.226093e+02  2.918353e+02  0.000000e+00  9.509224e+02  9.819250e+02  1.090808e+03  1.227564e+03
sensor_24            220304.0  5.562354e+02  1.822980e+02  0.000000e+00  6.011511e+02  6.258735e+02  6.286077e+02  1.000000e+03
sensor_25            220284.0  6.491448e+02  2.208652e+02  0.000000e+00  6.939578e+02  7.402035e+02  7.503571e+02  8.395750e+02
sensor_26            220300.0  7.864118e+02  2.466636e+02  4.315479e+01  7.904896e+02  8.618696e+02  9.191048e+02  1.214420e+03
sensor_27            220304.0  5.015066e+02  1.698232e+02  0.000000e+00  4.482980e+02  4.944684e+02  5.362745e+02  2.000000e+03
sensor_28            220304.0  8.516903e+02  3.130740e+02  4.319347e+00  7.826826e+02  9.672799e+02  1.043977e+03  1.841146e+03
sensor_29            220248.0  5.761953e+02  2.257641e+02  6.365742e-01  5.189472e+02  5.648725e+02  7.440215e+02  1.466281e+03
sensor_30            220059.0  6.145964e+02  1.957269e+02  0.000000e+00  6.277778e+02  6.689814e+02  6.972222e+02  1.600000e+03
sensor_31            220304.0  8.633231e+02  2.835448e+02  2.395833e+01  8.390624e+02  9.177083e+02  9.812499e+02  1.800000e+03
sensor_32            220252.0  8.042839e+02  2.606024e+02  2.407161e-01  7.606075e+02  8.788508e+02  9.438776e+02  1.839211e+03
sensor_33            220304.0  4.864060e+02  1.507518e+02  6.460602e+00  4.897611e+02  5.122717e+02  5.551632e+02  1.578600e+03
sensor_34            220304.0  2.349718e+02  8.837606e+01  5.488237e+01  1.724863e+02  2.263560e+02  3.168449e+02  4.255498e+02
sensor_35            220304.0  4.271298e+02  1.417725e+02  0.000000e+00  3.531766e+02  4.733493e+02  5.288910e+02  6.944791e+02
sensor_36            220304.0  5.930339e+02  2.893855e+02  2.260970e+00  2.885476e+02  7.096680e+02  8.373330e+02  9.840607e+02
sensor_37            220304.0  6.078736e+01  3.760488e+01  0.000000e+00  2.879922e+01  6.429548e+01  9.082193e+01  1.749012e+02
sensor_38            220293.0  4.965595e+01  1.054040e+01  2.447917e+01  4.557291e+01  4.947916e+01  5.364583e+01  4.177083e+02
sensor_39            220293.0  3.661044e+01  1.561372e+01  1.927083e+01  3.255208e+01  3.541666e+01  3.906250e+01  5.479166e+02
sensor_40            220293.0  6.884453e+01  2.137114e+01  2.343750e+01  5.781250e+01  6.640625e+01  7.786458e+01  5.127604e+02
sensor_41            220293.0  3.536513e+01  7.898665e+00  2.083333e+01  3.255208e+01  3.489583e+01  3.776041e+01  4.203125e+02
sensor_42            220293.0  3.545346e+01  1.025952e+01  2.213542e+01  3.281250e+01  3.515625e+01  3.697916e+01  3.742188e+02
sensor_43            220293.0  4.387959e+01  1.104440e+01  2.447917e+01  3.958333e+01  4.296875e+01  4.661458e+01  4.085937e+02
sensor_44            220293.0  4.265688e+01  1.157636e+01  2.575232e+01  3.674768e+01  4.050926e+01  4.513889e+01  1.000000e+03
sensor_45            220293.0  4.309498e+01  1.283752e+01  2.633102e+01  3.674768e+01  4.021991e+01  4.484954e+01  3.203125e+02
sensor_46            220293.0  4.801859e+01  1.564128e+01  2.633102e+01  4.050926e+01  4.484954e+01  5.121528e+01  3.703704e+02
sensor_47            220293.0  4.434090e+01  1.044244e+01  2.719907e+01  3.906250e+01  4.253472e+01  4.658565e+01  3.035301e+02
sensor_48            220293.0  1.508890e+02  8.224496e+01  2.633102e+01  8.391203e+01  1.380208e+02  2.083333e+02  5.616320e+02
sensor_49            220293.0  5.711997e+01  1.914360e+01  2.662037e+01  4.774306e+01  5.266204e+01  6.076389e+01  4.644097e+02
sensor_50            143303.0  1.830493e+02  6.525865e+01  2.748843e+01  1.675347e+02  1.938657e+02  2.199074e+02  1.000000e+03
sensor_51            204937.0  2.026997e+02  1.095886e+02  2.777778e+01  1.791088e+02  1.973380e+02  2.167245e+02  1.000000e+03

=== Get Top Sample Rows

,meta__dataset,meta__split,meta__run_id,meta__asset_id,meta__ingested_at_utc,meta__source_file,meta__source_row_id,meta__record_id,meta__truth_hash,meta__parent_truth_hash,meta__pipeline_mode,Unnamed: 0,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,sensor_09,sensor_10,sensor_11,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,sensor_22,sensor_23,sensor_24,sensor_25,sensor_26,sensor_27,sensor_28,sensor_29,sensor_30,sensor_31,sensor_32,sensor_33,sensor_34,sensor_35,sensor_36,sensor_37,sensor_38,sensor_39,sensor_40,sensor_41,sensor_42,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
0,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,0,14598431322315673869,72a94a9e57899cc4364af8a15ee451b148cffe19579a09...,None,batch,0,2018-04-01 00:00:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,15.05353,37.22740,47.52422,31.11716,1.681353,419.5747,NaN,461.8781,466.3284,2.565284,665.3993,398.9862,880.0001,498.8926,975.9409,627.6740,741.7151,848.0708,429.0377,785.1935,684.9443,594.4445,682.8125,680.4416,433.7037,171.9375,341.9039,195.0655,90.32386,40.36458,31.51042,70.57291,30.98958,31.770832,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,1,15954729095895098000,72a94a9e57899cc4364af8a15ee451b148cffe19579a09...,None,batch,1,2018-04-01 00:01:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,15.05353,37.22740,47.52422,31.11716,1.681353,419.5747,NaN,461.8781,466.3284,2.565284,665.3993,398.9862,880.0001,498.8926,975.9409,627.6740,741.7151,848.0708,429.0377,785.1935,684.9443,594.4445,682.8125,680.4416,433.7037,171.9375,341.9039,195.0655,90.32386,40.36458,31.51042,70.57291,30.98958,31.770832,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,2,10041703297090838359,72a94a9e57899cc4364af8a15ee451b148cffe19579a09...,None,batch,2,2018-04-01 00:02:00,2.444734,47.35243,53.2118,46.397570,638.8889,73.54598,13.32465,16.03733,15.61777,15.01013,37.86777,48.17723,32.08894,1.708474,420.8480,NaN,462.7798,459.6364,2.500062,666.2234,399.9418,880.4237,501.3617,982.7342,631.1326,740.8031,849.8997,454.2390,778.5734,715.6266,661.5740,721.8750,694.7721,441.2635,169.9820,343.1955,200.9694,93.90508,41.40625,31.25000,69.53125,30.46875,31.770830,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL
3,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,3,2072036352569063261,72a94a9e57899cc4364af8a15ee451b148cffe19579a09...,None,batch,3,2018-04-01 00:03:00,2.460474,47.09201,53.1684,46.397568,628.1250,76.98898,13.31742,16.24711,15.69734,15.08247,38.57977,48.65607,31.67221,1.579427,420.7494,NaN,462.8980,460.8858,2.509521,666.0114,399.1046,878.8917,499.0430,977.7520,625.4076,739.2722,847.7579,474.8731,779.5091,690.4011,686.1111,754.6875,683.3831,446.2493,166.4987,343.9586,193.1689,101.04060,41.92708,31.51042,72.13541,30.46875,31.510420,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL
4,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,4,4365040424004714369,72a94a9e57899cc4364af8a15ee451b148cffe19579a09...,None,batch,4,2018-04-01 00:04:00,2.445718,47.13541,53.2118,46.397568,636.4583,76.58897,13.35359,16.21094,15.69734,15.08247,39.48939,49.06298,31.95202,1.683831,419.8926,NaN,461.4906,468.2206,2.604785,663.2111,400.5426,882.5874,498.5383,979.5755,627.1830,737.6033,846.9182,408.8159,785.2307,704.6937,631.4814,766.1458,702.4431,433.9081,164.7498,339.9630,193.8770,101.70380,42.70833,31.51042,76.82291,30.98958,31.510420,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL

## Silver

### Pre-EDA

In [2]:
%run ./eda/EDA_Notebook_Pump_Silver_01_PreEDA.ipynb

/opt/miniconda/envs/capstone/lib/python3.10/site-packages/nbformat/__init__.py:96: MissingIDFieldWarning: Cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)
2026-04-20 14:45:46,287 | INFO | capstone.silver | Silver stage starting
2026-04-20 14:45:46,289 | INFO | capstone.silver | Project Root Path Loaded: /workspace
2026-04-20 14:45:46,290 | INFO | capstone.silver | Project Logging Path Loaded: /workspace/logs
2026-04-20 14:45:46,292 | INFO | capstone.silver | Project Artifacts Path Loaded: /workspace/artifacts
2026-04-20 14:45:46,293 | INFO | capstone.silver | Project Notebooks Path Loaded: /workspace/notebooks
2026-04-20 14:45:46,294 | INFO | capstone.silver | Project Truths Path Loaded: /workspace/artifacts/truths
2026-04-20 14:45:46,295 | INFO | capstone.silver | Project Data Path Loaded: /workspace/data
2026-04-20 14:45:46,297 | INFO | capstone.silver | Previous Layer (Bronze) Path Loaded: /workspace/data/bronze
2026-04-20 14:45:46,298 | INFO | capstone.silver | Previous Layer (Bronze) Training Path Loaded: /workspace/data/bronze/train
2026-04-20 14:45:46,299 | INFO | capstone.silver | Previous Layer (Bronze) Testing Path Loaded: /workspace/data/bronze/test
2026-04-20 14:45:46,301 | INFO | capstone.silver | Data Silver Path Loaded: /workspace/data/silver
2026-04-20 14:45:46,303 | INFO | capstone.silver | Data Silver Training Path Loaded: /workspace/data/silver/train
2026-04-20 14:45:46,305 | INFO | capstone.silver | Data Silver Testing Path Loaded: /workspace/data/silver/test

2026-04-20 14:45:47,682 | INFO | capstone.silver | W&B initialized: silver__001
2026-04-20 14:45:47,685 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:45:47.685759+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'step', 'step': 'init', 'message': 'Initialized ledger', 'why': None, 'consequence': None, 'data': {}}
2026-04-20 14:45:47,699 | INFO | capstone.file_io | Loading Parquet: /workspace/data/bronze/train/pump__bronze__train.parquet
2026-04-20 14:45:48,847 | INFO | capstone.silver | Loaded Bronze: /workspace/data/bronze/train/pump__bronze__train.parquet | shape=(220320, 66)
2026-04-20 14:45:48,853 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:45:48.853200+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'step', 'step': 'load_bronze', 'message': 'Loaded Bronze Parquet', 'why': 'Silver must be derived from reprodicible Bronze Artifact', 'consequence': 'All silver outputs trace back to this file', 'data': {'bronze_path': '/workspace/data/bronze/train/pump__bronze__train.parquet', 'shape': [220320, 66], 'cols': 66}}

,meta__dataset,meta__split,meta__run_id,meta__asset_id,meta__ingested_at_utc,meta__source_file,meta__source_row_id,meta__record_id,meta__truth_hash,meta__parent_truth_hash,meta__pipeline_mode,Unnamed: 0,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,sensor_09,sensor_10,sensor_11,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,sensor_22,sensor_23,sensor_24,sensor_25,sensor_26,sensor_27,sensor_28,sensor_29,sensor_30,sensor_31,sensor_32,sensor_33,sensor_34,sensor_35,sensor_36,sensor_37,sensor_38,sensor_39,sensor_40,sensor_41,sensor_42,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
0,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,0,14598431322315673869,72a94a9e57899cc4364af8a15ee451b148cffe19579a09...,None,batch,0,2018-04-01 00:00:00,2.465394,47.09201,53.2118,46.31076,634.3750,76.45975,13.41146,16.13136,15.56713,15.05353,37.22740,47.52422,31.11716,1.681353,419.5747,NaN,461.8781,466.3284,2.565284,665.3993,398.9862,880.0001,498.8926,975.9409,627.6740,741.7151,848.0708,429.0377,785.1935,684.9443,594.4445,682.8125,680.4416,433.7037,171.9375,341.9039,195.0655,90.32386,40.36458,31.51042,70.57291,30.98958,31.770832,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,1,15954729095895098000,72a94a9e57899cc4364af8a15ee451b148cffe19579a09...,None,batch,1,2018-04-01 00:01:00,2.465394,47.09201,53.2118,46.31076,634.3750,76.45975,13.41146,16.13136,15.56713,15.05353,37.22740,47.52422,31.11716,1.681353,419.5747,NaN,461.8781,466.3284,2.565284,665.3993,398.9862,880.0001,498.8926,975.9409,627.6740,741.7151,848.0708,429.0377,785.1935,684.9443,594.4445,682.8125,680.4416,433.7037,171.9375,341.9039,195.0655,90.32386,40.36458,31.51042,70.57291,30.98958,31.770832,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,pump,unsplit,run__001,asset__001,2026-04-20 14:45:09.221726+00:00,sensor.csv,2,10041703297090838359,72a94a9e57899cc4364af8a15ee451b148cffe19579a09...,None,batch,2,2018-04-01 00:02:00,2.444734,47.35243,53.2118,46.39757,638.8889,73.54598,13.32465,16.03733,15.61777,15.01013,37.86777,48.17723,32.08894,1.708474,420.8480,NaN,462.7798,459.6364,2.500062,666.2234,399.9418,880.4237,501.3617,982.7342,631.1326,740.8031,849.8997,454.2390,778.5734,715.6266,661.5740,721.8750,694.7721,441.2635,169.9820,343.1955,200.9694,93.90508,41.40625,31.25000,69.53125,30.46875,31.770830,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL

2026-04-20 14:45:49,104 | INFO | capstone.silver | Resolved Bronze parent truth hash: 72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976
2026-04-20 14:45:49,107 | INFO | capstone.silver | Resolved Silver dataset name from Bronze truth: pump

Silver parent truth hash: 72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976
Silver dataset name from parent truth: pump
=== Silver Pre-EDA: Data Overview ===
Shape: 220,320 rows × 66 columns

=== Column Types ===

                                       dtype
meta__dataset                       category
meta__split                         category
meta__run_id                          object
meta__asset_id                        object
meta__ingested_at_utc    datetime64[us, UTC]
meta__source_file             string[python]
meta__source_row_id                    int64
meta__record_id                       uint64
meta__truth_hash                      object
meta__parent_truth_hash               object
meta__pipeline_mode                   object
Unnamed: 0                             int64
timestamp                             object
sensor_00                            float64
sensor_01                            float64
sensor_02                            float64
sensor_03                            float64
sensor_04                            float64
sensor_05                            float64
sensor_06                            float64

=== df.info() ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220320 entries, 0 to 220319
Data columns (total 66 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   meta__dataset            220320 non-null  category
 1   meta__split              220320 non-null  category
 2   meta__run_id             220320 non-null  object
 3   meta__asset_id           220320 non-null  object
 4   meta__ingested_at_utc    220320 non-null  datetime64[us, UTC]
 5   meta__source_file        220320 non-null  string
 6   meta__source_row_id      220320 non-null  int64
 7   meta__record_id          220320 non-null  uint64
 8   meta__truth_hash         220320 non-null  object
 9   meta__parent_truth_hash  0 non-null       object
 10  meta__pipeline_mode      220320 non-null  object
 11  Unnamed: 0               220320 non-null  int64
 12  timestamp                220320 non-null  object
 13  sensor_00                210112 non-null  float64
 14  sensor_01                219951 non-null  float64
 15  sensor_02                220301 non-null  float64
 16  sensor_03                220301 non-null  float64
 17  sensor_04                220301 non-null  float64
 18  sensor_05                220301 non-null  float64
 19  sensor_06                215522 non-null  float64
 20  sensor_07                214869 non-null  float64
 21  sensor_08                215213 non-null  float64
 22  sensor_09                215725 non-null  float64
 23  sensor_10                220301 non-null  float64
 24  sensor_11                220301 non-null  float64
 25  sensor_12                220301 non-null  float64
 26  sensor_13                220301 non-null  float64
 27  sensor_14                220299 non-null  float64
 28  sensor_15                0 non-null       float64
 29  sensor_16                220289 non-null  float64
 30  sensor_17                220274 non-null  float64
 31  sensor_18                220274 non-null  float64
 32  sensor_19                220304 non-null  float64
 33  sensor_20                220304 non-null  float64
 34  sensor_21                220304 non-null  float64
 35  sensor_22                220279 non-null  float64
 36  sensor_23                220304 non-null  float64
 37  sensor_24                220304 non-null  float64
 38  sensor_25                220284 non-null  float64
 39  sensor_26                220300 non-null  float64
 40  sensor_27                220304 non-null  float64
 41  sensor_28                220304 non-null  float64
 42  sensor_29                220248 non-null  float64
 43  sensor_30                220059 non-null  float64
 44  sensor_31                220304 non-null  float64
 45  sensor_32                220252 non-null  float64
 46  sensor_33                220304 non-null  float64
 47  sensor_34                220304 non-null  float64
 48  sensor_35                220304 non-null  float64
 49  sensor_36                220304 non-null  float64
 50  sensor_37                220304 non-null  float64
 51  sensor_38                220293 non-null  float64
 52  sensor_39                220293 non-null  float64
 53  sensor_40                220293 non-null  float64
 54  sensor_41                220293 non-null  float64
 55  sensor_42                220293 non-null  float64
 56  sensor_43                220293 non-null  float64
 57  sensor_44                220293 non-null  float64
 58  sensor_45                220293 non-null  float64
 59  sensor_46                220293 non-null  float64
 60  sensor_47                220293 non-null  float64
 61  sensor_48                220293 non-null  float64
 62  sensor_49                220293 non-null  float64
 63  sensor_50                143303 non-null  float64
 64  sensor_51                204937 non-null  float64
 65  machine_status           220320 non-null  object
dtypes: category(2), datetime64[us, UTC](1), float64(52), int64(2), object(7), string(1), uint64(1)
memory usage: 108.0+ MB

=== Basic Descriptive Statistics (numeric only) ===

                        count          mean           std           min           25%           50%           75%           max
meta__source_row_id  220320.0  1.101595e+05  6.360105e+04  0.000000e+00  5.507975e+04  1.101595e+05  1.652392e+05  2.203190e+05
meta__record_id      220320.0  9.224243e+18  5.322367e+18  1.873763e+14  4.610703e+18  9.220552e+18  1.381850e+19  1.844674e+19
Unnamed: 0           220320.0  1.101595e+05  6.360105e+04  0.000000e+00  5.507975e+04  1.101595e+05  1.652392e+05  2.203190e+05
sensor_00            210112.0  2.372221e+00  4.122274e-01  0.000000e+00  2.438831e+00  2.456539e+00  2.499826e+00  2.549016e+00
sensor_01            219951.0  4.759161e+01  3.296666e+00  0.000000e+00  4.631076e+01  4.813368e+01  4.947916e+01  5.672743e+01
sensor_02            220301.0  5.086739e+01  3.666820e+00  3.315972e+01  5.039062e+01  5.164930e+01  5.277777e+01  5.603299e+01
sensor_03            220301.0  4.375248e+01  2.418887e+00  3.164062e+01  4.283854e+01  4.422743e+01  4.531250e+01  4.822049e+01
sensor_04            220301.0  5.906739e+02  1.440239e+02  2.798032e+00  6.266204e+02  6.326389e+02  6.376157e+02  8.000000e+02
sensor_05            220301.0  7.339641e+01  1.729825e+01  0.000000e+00  6.997626e+01  7.557679e+01  8.091215e+01  9.999988e+01
sensor_06            215522.0  1.350154e+01  2.163736e+00  1.446759e-02  1.334635e+01  1.364294e+01  1.453993e+01  2.225116e+01
sensor_07            214869.0  1.584315e+01  2.201155e+00  0.000000e+00  1.590712e+01  1.616753e+01  1.642795e+01  2.359664e+01
sensor_08            215213.0  1.520072e+01  2.037390e+00  2.893518e-02  1.518374e+01  1.549479e+01  1.569734e+01  2.434896e+01
sensor_09            215725.0  1.479921e+01  2.091963e+00  0.000000e+00  1.505353e+01  1.508247e+01  1.511863e+01  2.500000e+01
sensor_10            220301.0  4.147034e+01  1.209352e+01  0.000000e+00  4.070526e+01  4.429134e+01  4.746376e+01  7.610686e+01
sensor_11            220301.0  4.191832e+01  1.305643e+01  0.000000e+00  3.885642e+01  4.536314e+01  4.965654e+01  6.000000e+01
sensor_12            220301.0  2.913697e+01  1.011394e+01  0.000000e+00  2.868681e+01  3.251583e+01  3.493973e+01  4.500000e+01
sensor_13            220301.0  7.078858e+00  6.901755e+00  0.000000e+00  1.538516e+00  2.929809e+00  1.285952e+01  3.118755e+01
sensor_14            220299.0  3.768600e+02  1.132064e+02  3.240955e+01  4.181033e+02  4.201062e+02  4.209971e+02  5.000000e+02
sensor_15                 0.0           NaN           NaN           NaN           NaN           NaN           NaN           NaN
sensor_16            220289.0  4.164729e+02  1.260726e+02  0.000000e+00  4.594534e+02  4.628561e+02  4.643027e+02  7.397415e+02
sensor_17            220274.0  4.211275e+02  1.291562e+02  0.000000e+00  4.541388e+02  4.620203e+02  4.668571e+02  5.999999e+02
sensor_18            220274.0  2.303785e+00  7.658831e-01  0.000000e+00  2.447542e+00  2.533704e+00  2.587682e+00  4.873250e+00
sensor_19            220304.0  5.908298e+02  1.993458e+02  0.000000e+00  6.627690e+02  6.656724e+02  6.671467e+02  8.789179e+02
sensor_20            220304.0  3.608052e+02  1.019741e+02  0.000000e+00  3.980215e+02  3.993670e+02  4.000884e+02  4.489079e+02
sensor_21            220304.0  7.962259e+02  2.266793e+02  9.552766e+01  8.754644e+02  8.796976e+02  8.821299e+02  1.107526e+03
sensor_22            220279.0  4.597928e+02  1.545283e+02  0.000000e+00  4.789626e+02  5.318559e+02  5.342549e+02  5.940611e+02
sensor_23            220304.0  9.226093e+02  2.918353e+02  0.000000e+00  9.509224e+02  9.819250e+02  1.090808e+03  1.227564e+03
sensor_24            220304.0  5.562354e+02  1.822980e+02  0.000000e+00  6.011511e+02  6.258735e+02  6.286077e+02  1.000000e+03
sensor_25            220284.0  6.491448e+02  2.208652e+02  0.000000e+00  6.939578e+02  7.402035e+02  7.503571e+02  8.395750e+02
sensor_26            220300.0  7.864118e+02  2.466636e+02  4.315479e+01  7.904896e+02  8.618696e+02  9.191048e+02  1.214420e+03
sensor_27            220304.0  5.015066e+02  1.698232e+02  0.000000e+00  4.482980e+02  4.944684e+02  5.362745e+02  2.000000e+03
sensor_28            220304.0  8.516903e+02  3.130740e+02  4.319347e+00  7.826826e+02  9.672799e+02  1.043977e+03  1.841146e+03
sensor_29            220248.0  5.761953e+02  2.257641e+02  6.365742e-01  5.189472e+02  5.648725e+02  7.440215e+02  1.466281e+03
sensor_30            220059.0  6.145964e+02  1.957269e+02  0.000000e+00  6.277778e+02  6.689814e+02  6.972222e+02  1.600000e+03
sensor_31            220304.0  8.633231e+02  2.835448e+02  2.395833e+01  8.390624e+02  9.177083e+02  9.812499e+02  1.800000e+03
sensor_32            220252.0  8.042839e+02  2.606024e+02  2.407161e-01  7.606075e+02  8.788508e+02  9.438776e+02  1.839211e+03
sensor_33            220304.0  4.864060e+02  1.507518e+02  6.460602e+00  4.897611e+02  5.122717e+02  5.551632e+02  1.578600e+03
sensor_34            220304.0  2.349718e+02  8.837606e+01  5.488237e+01  1.724863e+02  2.263560e+02  3.168449e+02  4.255498e+02
sensor_35            220304.0  4.271298e+02  1.417725e+02  0.000000e+00  3.531766e+02  4.733493e+02  5.288910e+02  6.944791e+02
sensor_36            220304.0  5.930339e+02  2.893855e+02  2.260970e+00  2.885476e+02  7.096680e+02  8.373330e+02  9.840607e+02
sensor_37            220304.0  6.078736e+01  3.760488e+01  0.000000e+00  2.879922e+01  6.429548e+01  9.082193e+01  1.749012e+02
sensor_38            220293.0  4.965595e+01  1.054040e+01  2.447917e+01  4.557291e+01  4.947916e+01  5.364583e+01  4.177083e+02
sensor_39            220293.0  3.661044e+01  1.561372e+01  1.927083e+01  3.255208e+01  3.541666e+01  3.906250e+01  5.479166e+02
sensor_40            220293.0  6.884453e+01  2.137114e+01  2.343750e+01  5.781250e+01  6.640625e+01  7.786458e+01  5.127604e+02
sensor_41            220293.0  3.536513e+01  7.898665e+00  2.083333e+01  3.255208e+01  3.489583e+01  3.776041e+01  4.203125e+02
sensor_42            220293.0  3.545346e+01  1.025952e+01  2.213542e+01  3.281250e+01  3.515625e+01  3.697916e+01  3.742188e+02
sensor_43            220293.0  4.387959e+01  1.104440e+01  2.447917e+01  3.958333e+01  4.296875e+01  4.661458e+01  4.085937e+02
sensor_44            220293.0  4.265688e+01  1.157636e+01  2.575232e+01  3.674768e+01  4.050926e+01  4.513889e+01  1.000000e+03
sensor_45            220293.0  4.309498e+01  1.283752e+01  2.633102e+01  3.674768e+01  4.021991e+01  4.484954e+01  3.203125e+02
sensor_46            220293.0  4.801859e+01  1.564128e+01  2.633102e+01  4.050926e+01  4.484954e+01  5.121528e+01  3.703704e+02
sensor_47            220293.0  4.434090e+01  1.044244e+01  2.719907e+01  3.906250e+01  4.253472e+01  4.658565e+01  3.035301e+02
sensor_48            220293.0  1.508890e+02  8.224496e+01  2.633102e+01  8.391203e+01  1.380208e+02  2.083333e+02  5.616320e+02
sensor_49            220293.0  5.711997e+01  1.914360e+01  2.662037e+01  4.774306e+01  5.266204e+01  6.076389e+01  4.644097e+02
sensor_50            143303.0  1.830493e+02  6.525865e+01  2.748843e+01  1.675347e+02  1.938657e+02  2.199074e+02  1.000000e+03
sensor_51            204937.0  2.026997e+02  1.095886e+02  2.777778e+01  1.791088e+02  1.973380e+02  2.167245e+02  1.000000e+03

2026-04-20 14:45:50,314 | INFO | capstone.silver | Dropped junk columns: ['Unnamed: 0']
2026-04-20 14:45:50,317 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:45:50.317764+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'step', 'step': 'remove_junk_import_columns', 'message': 'Dropped junk columns via candidates and/or regex pattern', 'why': None, 'consequence': None, 'data': {'dropped': ['Unnamed: 0'], 'pattern': '^unnamed:\\s*\\d+(\\.\\d+)?$'}}
2026-04-20 14:45:50,386 | INFO | capstone.silver | No duplicate column names detected.
2026-04-20 14:45:50,389 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:45:50.389758+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'step', 'step': 'deduplicate_columns', 'message': 'Removed duplicate column names (kept first occurrence).', 'why': None, 'consequence': None, 'data': {'duplicates': [], 'count': 0}}
2026-04-20 14:45:50,479 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:45:50.479627+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'decision', 'step': 'validate_dataset_name', 'message': 'Validated Bronze-stamped dataset name for Silver against parent truth and recorded the validation in Truth Store.', 'why': None, 'consequence': None, 'data': {'dataset_name': 'pump', 'dataset_source_col': 'meta__dataset', 'dataset_method': 'unique'}}
2026-04-20 14:45:50,535 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:45:50.535471+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'step', 'step': 'silver_meta_contract', 'message': 'Ensured required row-level/source meta exists. Silver runtime metadata is being stored in Truth Store, not row-stamped.', 'why': None, 'consequence': None, 'data': {'required_meta_columns': ['meta__dataset', 'meta__split', 'meta__run_id', 'meta__asset_id', 'meta__source_file', 'meta__source_row_id', 'meta__ingested_at_utc', 'meta__record_id'], 'processed_at_utc': '2026-04-20T14:45:50.534798+00:00', 'shape': {'rows': 220320, 'cols': 65}}}
2026-04-20 14:45:50,571 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:45:50.571500+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'decision', 'step': 'resolve_label_or_status_source', 'message': 'Resolved label/status source and wrote the resolution to Truth Store.', 'why': None, 'consequence': None, 'data': {'label_source_col': 'machine_status', 'label_source_type': 'status', 'found_label_columns': [], 'found_status_columns': ['machine_status'], 'has_label_candidates': 0, 'has_status_candidates': 1, 'chosen_summary': {'top_values': {'NORMAL': 205836, 'RECOVERING': 14477, 'BROKEN': 7}, 'unique_count': 3, 'non_null_count': 220320, 'total_row_count': 220320, 'coverage_pct': 100.0}}}
2026-04-20 14:45:50,653 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:45:50.653018+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'step', 'step': 'canonical_name_collision_protection', 'message': 'No canonical-name collisions found (Policy A).', 'why': 'Confirm input does not contain columns that conflict with canonical outputs.', 'consequence': 'Canonical outputs can be created without renaming any source columns.', 'data': {'policy': 'A', 'canonical_outputs': ['event_time', 'event_step', 'time_index'], 'collisions': 0, 'shape': {'rows': 220320, 'cols': 65}}}
2026-04-20 14:45:51,361 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:45:51.361757+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'decision', 'step': 'build_canonical_identity_and_order_master', 'message': 'Built canonical identity + ordering master and wrote the resolution to Truth Store.', 'why': None, 'consequence': None, 'data': {'dataset_name': 'pump', 'time_candidates': ['timestamp', 'event_time', 'time', 'datetime', 'date'], 'step_candidates': ['cycle', 'step', 'event_step', 'sample', 'time_index'], 'tie_breaker_candidates': ['meta__source_row_id', 'meta__record_id'], 'ordering_mode': 'time', 'group_columns': ['meta__asset_id', 'meta__run_id'], 'group_count': 1, 'rows': 220320, 'time_column_used': 'timestamp', 'time_parse_success_percent': 100.0, 'step_column_used': None, 'step_parse_success_percent': None, 'tie_breaker_column_used': 'meta__source_row_id', 'sorted': True, 'sort_columns': ['meta__asset_id', 'meta__run_id', 'event_time', 'meta__source_row_id'], 'shape': {'rows': 220320, 'cols': 70}}}
2026-04-20 14:45:51,573 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:45:51.573077+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'step', 'step': 'build_anomaly_flag', 'message': 'Built anomaly_flag from resolved label/status source.', 'why': 'Silver requires a consistent binary anomaly flag for segmentation, evaluation, and synthetic anomaly generation.', 'consequence': 'Downstream steps can rely on anomaly_flag (0/1) being present across datasets.', 'data': {'label_source_column': 'machine_status', 'label_source_type': 'status', 'source_type': 'status', 'source_column': 'machine_status', 'method': 'status_compare_to_normal_value', 'normal_value': 'NORMAL', 'unique_status_count': 3, 'non_null_count': 220320, 'anomaly_flag_counts': {'0': 205836, '1': 14484}, 'anomaly_rate_percent': 6.5740740740740735, 'shape': {'rows': 220320, 'columns': 74}}}
2026-04-20 14:45:51,589 | INFO | capstone.silver | Building episode ids from anomaly_flag for Silver dataframe.
2026-04-20 14:46:10,308 | INFO | capstone.silver | Episode id summary: {0: 18100, 1: 9521, 2: 43010, 3: 7765, 4: 58035, 5: 4742, 6: 25343, 7: 53804}
2026-04-20 14:46:10,311 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:46:10.311634+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'step', 'step': 'silver_build_episode_ids', 'message': 'Built meta__episode_id for Silver dataframe using anomaly windows.', 'why': None, 'consequence': None, 'data': {'episode_column': 'meta__episode_id', 'unique_episode_count': 8}}
/tmp/ipykernel_3817485/2158907718.py:25: DeprecationWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  or pd.api.types.is_categorical_dtype(silver_dataframe[column_name])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220320 entries, 0 to 220319
Data columns (total 75 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   meta__dataset            220320 non-null  category
 1   meta__split              220320 non-null  category
 2   meta__run_id             220320 non-null  object
 3   meta__asset_id           220320 non-null  object
 4   meta__ingested_at_utc    220320 non-null  datetime64[us, UTC]
 5   meta__source_file        220320 non-null  string
 6   meta__source_row_id      220320 non-null  int64
 7   meta__record_id          220320 non-null  uint64
 8   meta__truth_hash         220320 non-null  object
 9   meta__parent_truth_hash  0 non-null       object
 10  meta__pipeline_mode      220320 non-null  object
 11  timestamp                220320 non-null  object
 12  sensor_00                210112 non-null  float64
 13  sensor_01                219951 non-null  float64
 14  sensor_02                220301 non-null  float64
 15  sensor_03                220301 non-null  float64
 16  sensor_04                220301 non-null  float64
 17  sensor_05                220301 non-null  float64
 18  sensor_06                215522 non-null  float64
 19  sensor_07                214869 non-null  float64
 20  sensor_08                215213 non-null  float64
 21  sensor_09                215725 non-null  float64
 22  sensor_10                220301 non-null  float64
 23  sensor_11                220301 non-null  float64
 24  sensor_12                220301 non-null  float64
 25  sensor_13                220301 non-null  float64
 26  sensor_14                220299 non-null  float64
 27  sensor_15                0 non-null       float64
 28  sensor_16                220289 non-null  float64
 29  sensor_17                220274 non-null  float64
 30  sensor_18                220274 non-null  float64
 31  sensor_19                220304 non-null  float64
 32  sensor_20                220304 non-null  float64
 33  sensor_21                220304 non-null  float64
 34  sensor_22                220279 non-null  float64
 35  sensor_23                220304 non-null  float64
 36  sensor_24                220304 non-null  float64
 37  sensor_25                220284 non-null  float64
 38  sensor_26                220300 non-null  float64
 39  sensor_27                220304 non-null  float64
 40  sensor_28                220304 non-null  float64
 41  sensor_29                220248 non-null  float64
 42  sensor_30                220059 non-null  float64
 43  sensor_31                220304 non-null  float64
 44  sensor_32                220252 non-null  float64
 45  sensor_33                220304 non-null  float64
 46  sensor_34                220304 non-null  float64
 47  sensor_35                220304 non-null  float64
 48  sensor_36                220304 non-null  float64
 49  sensor_37                220304 non-null  float64
 50  sensor_38                220293 non-null  float64
 51  sensor_39                220293 non-null  float64
 52  sensor_40                220293 non-null  float64
 53  sensor_41                220293 non-null  float64
 54  sensor_42                220293 non-null  float64
 55  sensor_43                220293 non-null  float64
 56  sensor_44                220293 non-null  float64
 57  sensor_45                220293 non-null  float64
 58  sensor_46                220293 non-null  float64
 59  sensor_47                220293 non-null  float64
 60  sensor_48                220293 non-null  float64
 61  sensor_49                220293 non-null  float64
 62  sensor_50                143303 non-null  float64
 63  sensor_51                204937 non-null  float64
 64  machine_status           220320 non-null  object
 65  event_time               220320 non-null  datetime64[ns, UTC]
 66  event_step               220320 non-null  int64
 67  time_index               220320 non-null  int64
 68  meta__event_id           220320 non-null  object
 69  event_date               220320 non-null  datetime64[ns, UTC]
 70  anomaly_flag             220320 non-null  int64
 71  status_normal_value      220320 non-null  object
 72  is_normal                220320 non-null  int64
 73  is_anomaly               220320 non-null  int64
 74  meta__episode_id         220320 non-null  int64
dtypes: category(2), datetime64[ns, UTC](2), datetime64[us, UTC](1), float64(52), int64(7), object(9), string(1), uint64(1)
memory usage: 123.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220320 entries, 0 to 220319
Data columns (total 75 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   meta__dataset            220320 non-null  category
 1   meta__split              220320 non-null  category
 2   meta__run_id             220320 non-null  object
 3   meta__asset_id           220320 non-null  object
 4   meta__ingested_at_utc    220320 non-null  datetime64[us, UTC]
 5   meta__source_file        220320 non-null  string
 6   meta__source_row_id      220320 non-null  int64
 7   meta__record_id          220320 non-null  uint64
 8   meta__truth_hash         220320 non-null  object
 9   meta__parent_truth_hash  0 non-null       object
 10  meta__pipeline_mode      220320 non-null  object
 11  timestamp                220320 non-null  object
 12  sensor_00                210112 non-null  float64
 13  sensor_01                219951 non-null  float64
 14  sensor_02                220301 non-null  float64
 15  sensor_03                220301 non-null  float64
 16  sensor_04                220301 non-null  float64
 17  sensor_05                220301 non-null  float64
 18  sensor_06                215522 non-null  float64
 19  sensor_07                214869 non-null  float64
 20  sensor_08                215213 non-null  float64
 21  sensor_09                215725 non-null  float64
 22  sensor_10                220301 non-null  float64
 23  sensor_11                220301 non-null  float64
 24  sensor_12                220301 non-null  float64
 25  sensor_13                220301 non-null  float64
 26  sensor_14                220299 non-null  float64
 27  sensor_15                0 non-null       float64
 28  sensor_16                220289 non-null  float64
 29  sensor_17                220274 non-null  float64
 30  sensor_18                220274 non-null  float64
 31  sensor_19                220304 non-null  float64
 32  sensor_20                220304 non-null  float64
 33  sensor_21                220304 non-null  float64
 34  sensor_22                220279 non-null  float64
 35  sensor_23                220304 non-null  float64
 36  sensor_24                220304 non-null  float64
 37  sensor_25                220284 non-null  float64
 38  sensor_26                220300 non-null  float64
 39  sensor_27                220304 non-null  float64
 40  sensor_28                220304 non-null  float64
 41  sensor_29                220248 non-null  float64
 42  sensor_30                220059 non-null  float64
 43  sensor_31                220304 non-null  float64
 44  sensor_32                220252 non-null  float64
 45  sensor_33                220304 non-null  float64
 46  sensor_34                220304 non-null  float64
 47  sensor_35                220304 non-null  float64
 48  sensor_36                220304 non-null  float64
 49  sensor_37                220304 non-null  float64
 50  sensor_38                220293 non-null  float64
 51  sensor_39                220293 non-null  float64
 52  sensor_40                220293 non-null  float64
 53  sensor_41                220293 non-null  float64
 54  sensor_42                220293 non-null  float64
 55  sensor_43                220293 non-null  float64
 56  sensor_44                220293 non-null  float64
 57  sensor_45                220293 non-null  float64
 58  sensor_46                220293 non-null  float64
 59  sensor_47                220293 non-null  float64
 60  sensor_48                220293 non-null  float64
 61  sensor_49                220293 non-null  float64
 62  sensor_50                143303 non-null  float64
 63  sensor_51                204937 non-null  float64
 64  machine_status           220320 non-null  object
 65  event_time               220320 non-null  datetime64[ns, UTC]
 66  event_step               220320 non-null  int64
 67  time_index               220320 non-null  int64
 68  meta__event_id           220320 non-null  object
 69  event_date               220320 non-null  datetime64[ns, UTC]
 70  anomaly_flag             220320 non-null  int64
 71  status_normal_value      220320 non-null  object
 72  is_normal                220320 non-null  int64
 73  is_anomaly               220320 non-null  int64
 74  meta__episode_id         220320 non-null  int64
dtypes: category(2), datetime64[ns, UTC](2), datetime64[us, UTC](1), float64(52), int64(7), object(9), string(1), uint64(1)
memory usage: 123.1+ MB

2026-04-20 14:46:11,740 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:46:11.740302+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'decision', 'step': 'missingness_quarantine', 'message': 'Dropped features exceeding missingness threshold (or all-null).', 'why': 'High-missingness features add noise/instability to EDA + modeling.', 'consequence': 'Feature set shrinks; synthetic generator will replicate missingness for dropped sensors.', 'data': {'threshold_pct': 30.0, 'dropped_count': 2, 'dropped_features': ['sensor_15', 'sensor_50'], 'drop_reasons': {'sensor_15': 'all_null', 'sensor_50': 'missing_rate_above_threshold'}, 'dropped_missing_pct': {'sensor_15': 100.0, 'sensor_50': 34.95688090050835}, 'remaining_count': 50, 'top_missing_pct': {'sensor_15': 100.0, 'sensor_50': 34.95688090050835, 'sensor_51': 6.982116920842412, 'sensor_00': 4.633260711692085, 'sensor_07': 2.474128540305011, 'sensor_08': 2.3179920116194626, 'sensor_06': 2.177741466957153, 'sensor_09': 2.0856027596223674, 'sensor_01': 0.16748366013071894, 'sensor_30': 0.1184640522875817}, 'missingness_pct_all': {'sensor_00': 4.633260711692085, 'sensor_01': 0.16748366013071894, 'sensor_02': 0.008623819898329702, 'sensor_03': 0.008623819898329702, 'sensor_04': 0.008623819898329702, 'sensor_05': 0.008623819898329702, 'sensor_06': 2.177741466957153, 'sensor_07': 2.474128540305011, 'sensor_08': 2.3179920116194626, 'sensor_09': 2.0856027596223674, 'sensor_10': 0.008623819898329702, 'sensor_11': 0.008623819898329702, 'sensor_12': 0.008623819898329702, 'sensor_13': 0.008623819898329702, 'sensor_14': 0.009531590413943355, 'sensor_16': 0.014070442992011621, 'sensor_17': 0.020878721859114015, 'sensor_18': 0.020878721859114015, 'sensor_19': 0.007262164124909223, 'sensor_20': 0.007262164124909223, 'sensor_21': 0.007262164124909223, 'sensor_22': 0.018609295570079884, 'sensor_23': 0.007262164124909223, 'sensor_24': 0.007262164124909223, 'sensor_25': 0.01633986928104575, 'sensor_26': 0.00907770515613653, 'sensor_27': 0.007262164124909223, 'sensor_28': 0.007262164124909223, 'sensor_29': 0.0326797385620915, 'sensor_30': 0.1184640522875817, 'sensor_31': 0.007262164124909223, 'sensor_32': 0.030864197530864196, 'sensor_33': 0.007262164124909223, 'sensor_34': 0.007262164124909223, 'sensor_35': 0.007262164124909223, 'sensor_36': 0.007262164124909223, 'sensor_37': 0.007262164124909223, 'sensor_38': 0.012254901960784314, 'sensor_39': 0.012254901960784314, 'sensor_40': 0.012254901960784314, 'sensor_41': 0.012254901960784314, 'sensor_42': 0.012254901960784314, 'sensor_43': 0.012254901960784314, 'sensor_44': 0.012254901960784314, 'sensor_45': 0.012254901960784314, 'sensor_46': 0.012254901960784314, 'sensor_47': 0.012254901960784314, 'sensor_48': 0.012254901960784314, 'sensor_49': 0.012254901960784314, 'sensor_51': 6.982116920842412}, 'missingness_pct_by_state': {'normal': {'sensor_00': 0.006801531316193475, 'sensor_01': 0.16469422258497057, 'sensor_02': 0.006801531316193475, 'sensor_03': 0.006801531316193475, 'sensor_04': 0.006801531316193475, 'sensor_05': 0.006801531316193475, 'sensor_06': 0.006801531316193475, 'sensor_07': 0.006801531316193475, 'sensor_08': 0.006801531316193475, 'sensor_09': 0.006801531316193475, 'sensor_10': 0.006801531316193475, 'sensor_11': 0.006801531316193475, 'sensor_12': 0.006801531316193475, 'sensor_13': 0.006801531316193475, 'sensor_14': 0.010202296974290212, 'sensor_16': 0.015060533628714123, 'sensor_17': 0.022347888610349986, 'sensor_18': 0.022347888610349986, 'sensor_19': 0.007773178647078256, 'sensor_20': 0.007773178647078256, 'sensor_21': 0.007773178647078256, 'sensor_22': 0.01991877028313803, 'sensor_23': 0.007773178647078256, 'sensor_24': 0.007773178647078256, 'sensor_25': 0.01748965195592608, 'sensor_26': 0.00971647330884782, 'sensor_27': 0.007773178647078256, 'sensor_28': 0.007773178647078256, 'sensor_29': 0.03497930391185216, 'sensor_30': 0.12679997668046405, 'sensor_31': 0.007773178647078256, 'sensor_32': 0.033036009250082585, 'sensor_33': 0.007773178647078256, 'sensor_34': 0.007773178647078256, 'sensor_35': 0.007773178647078256, 'sensor_36': 0.007773178647078256, 'sensor_37': 0.007773178647078256, 'sensor_38': 0.010688120639732603, 'sensor_39': 0.010688120639732603, 'sensor_40': 0.010688120639732603, 'sensor_41': 0.010688120639732603, 'sensor_42': 0.010688120639732603, 'sensor_43': 0.010688120639732603, 'sensor_44': 0.010688120639732603, 'sensor_45': 0.010688120639732603, 'sensor_46': 0.010688120639732603, 'sensor_47': 0.010688120639732603, 'sensor_48': 0.010688120639732603, 'sensor_49': 0.010688120639732603, 'sensor_51': 6.016440272838571}, 'abnormal': {'sensor_00': 0.0, 'sensor_01': 0.0, 'sensor_02': 0.0, 'sensor_03': 0.0, 'sensor_04': 0.0, 'sensor_05': 0.0, 'sensor_06': 0.0, 'sensor_07': 0.0, 'sensor_08': 0.0, 'sensor_09': 0.0, 'sensor_10': 0.0, 'sensor_11': 0.0, 'sensor_12': 0.0, 'sensor_13': 0.0, 'sensor_14': 0.0, 'sensor_16': 0.0, 'sensor_17': 0.0, 'sensor_18': 0.0, 'sensor_19': 0.0, 'sensor_20': 0.0, 'sensor_21': 0.0, 'sensor_22': 0.0, 'sensor_23': 0.0, 'sensor_24': 0.0, 'sensor_25': 0.0, 'sensor_26': 0.0, 'sensor_27': 0.0, 'sensor_28': 0.0, 'sensor_29': 0.0, 'sensor_30': 0.0, 'sensor_31': 0.0, 'sensor_32': 0.0, 'sensor_33': 0.0, 'sensor_34': 0.0, 'sensor_35': 0.0, 'sensor_36': 0.0, 'sensor_37': 0.0, 'sensor_38': 0.0, 'sensor_39': 0.0, 'sensor_40': 0.0, 'sensor_41': 0.0, 'sensor_42': 0.0, 'sensor_43': 0.0, 'sensor_44': 0.0, 'sensor_45': 0.0, 'sensor_46': 0.0, 'sensor_47': 0.0, 'sensor_48': 0.0, 'sensor_49': 0.0, 'sensor_51': 14.285714285714285}, 'recovery': {'sensor_00': 70.41514125854805, 'sensor_01': 0.20722525385093596, 'sensor_02': 0.03453754230848933, 'sensor_03': 0.03453754230848933, 'sensor_04': 0.03453754230848933, 'sensor_05': 0.03453754230848933, 'sensor_06': 33.04552048076259, 'sensor_07': 37.556123506251296, 'sensor_08': 35.179940595427226, 'sensor_09': 31.643296263037925, 'sensor_10': 0.03453754230848933, 'sensor_11': 0.03453754230848933, 'sensor_12': 0.03453754230848933, 'sensor_13': 0.03453754230848933, 'sensor_14': 0.0, 'sensor_16': 0.0, 'sensor_17': 0.0, 'sensor_18': 0.0, 'sensor_19': 0.0, 'sensor_20': 0.0, 'sensor_21': 0.0, 'sensor_22': 0.0, 'sensor_23': 0.0, 'sensor_24': 0.0, 'sensor_25': 0.0, 'sensor_26': 0.0, 'sensor_27': 0.0, 'sensor_28': 0.0, 'sensor_29': 0.0, 'sensor_30': 0.0, 'sensor_31': 0.0, 'sensor_32': 0.0, 'sensor_33': 0.0, 'sensor_34': 0.0, 'sensor_35': 0.0, 'sensor_36': 0.0, 'sensor_37': 0.0, 'sensor_38': 0.03453754230848933, 'sensor_39': 0.03453754230848933, 'sensor_40': 0.03453754230848933, 'sensor_41': 0.03453754230848933, 'sensor_42': 0.03453754230848933, 'sensor_43': 0.03453754230848933, 'sensor_44': 0.03453754230848933, 'sensor_45': 0.03453754230848933, 'sensor_46': 0.03453754230848933, 'sensor_47': 0.03453754230848933, 'sensor_48': 0.03453754230848933, 'sensor_49': 0.03453754230848933, 'sensor_51': 20.708710368170202}}, 'missingness_state_dependent_flag': {'sensor_00': False, 'sensor_01': False, 'sensor_02': False, 'sensor_03': False, 'sensor_04': False, 'sensor_05': False, 'sensor_06': False, 'sensor_07': False, 'sensor_08': False, 'sensor_09': False, 'sensor_10': False, 'sensor_11': False, 'sensor_12': False, 'sensor_13': False, 'sensor_14': False, 'sensor_16': False, 'sensor_17': False, 'sensor_18': False, 'sensor_19': False, 'sensor_20': False, 'sensor_21': False, 'sensor_22': False, 'sensor_23': False, 'sensor_24': False, 'sensor_25': False, 'sensor_26': False, 'sensor_27': False, 'sensor_28': False, 'sensor_29': False, 'sensor_30': False, 'sensor_31': False, 'sensor_32': False, 'sensor_33': False, 'sensor_34': False, 'sensor_35': False, 'sensor_36': False, 'sensor_37': False, 'sensor_38': False, 'sensor_39': False, 'sensor_40': False, 'sensor_41': False, 'sensor_42': False, 'sensor_43': False, 'sensor_44': False, 'sensor_45': False, 'sensor_46': False, 'sensor_47': False, 'sensor_48': False, 'sensor_49': False, 'sensor_51': False}, 'missingness_state_gate_params': {'diff_gate_pct': 5.0, 'min_rows_per_state_for_gate': 200, 'rows_by_state': {'normal': 205836, 'abnormal': 7, 'recovery': 14477}, 'state_list': ['normal', 'abnormal', 'recovery'], 'state_col_resolved': 'machine_status', 'state_col_synth': 'machine_status__synethic', 'state_map': {'normal': 'normal', 'broken': 'abnormal', 'recovering': 'recovery'}}}}
2026-04-20 14:46:11,760 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:46:11.760447+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'decision', 'step': 'finalize_feature_set', 'message': 'Finalized feature set and wrote feature set metadata to Truth Store.', 'why': None, 'consequence': None, 'data': {'feature_set_id': 'feature_set__bea5fdd737ae53fcd80ca84cafcd0c40', 'label_source_column': 'machine_status', 'label_source_type': 'status', 'exclude_prefixes': ['meta__', 'raw__'], 'exclude_columns': ['event_time', 'event_step', 'time_index', 'event_date', 'meta__event_id', 'anomaly_flag', 'is_anomaly', 'is_normal', 'status_normal_value'], 'feature_count': 50, 'selected_feature_columns': ['sensor_00', 'sensor_01', 'sensor_02', 'sensor_03', 'sensor_04', 'sensor_05', 'sensor_06', 'sensor_07', 'sensor_08', 'sensor_09', 'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21', 'sensor_22', 'sensor_23', 'sensor_24', 'sensor_25', 'sensor_26', 'sensor_27', 'sensor_28', 'sensor_29', 'sensor_30', 'sensor_31', 'sensor_32', 'sensor_33', 'sensor_34', 'sensor_35', 'sensor_36', 'sensor_37', 'sensor_38', 'sensor_39', 'sensor_40', 'sensor_41', 'sensor_42', 'sensor_43', 'sensor_44', 'sensor_45', 'sensor_46', 'sensor_47', 'sensor_48', 'sensor_49', 'sensor_51'], 'feature_groups': {'numeric': ['sensor_00', 'sensor_01', 'sensor_02', 'sensor_03', 'sensor_04', 'sensor_05', 'sensor_06', 'sensor_07', 'sensor_08', 'sensor_09', 'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21', 'sensor_22', 'sensor_23', 'sensor_24', 'sensor_25', 'sensor_26', 'sensor_27', 'sensor_28', 'sensor_29', 'sensor_30', 'sensor_31', 'sensor_32', 'sensor_33', 'sensor_34', 'sensor_35', 'sensor_36', 'sensor_37', 'sensor_38', 'sensor_39', 'sensor_40', 'sensor_41', 'sensor_42', 'sensor_43', 'sensor_44', 'sensor_45', 'sensor_46', 'sensor_47', 'sensor_48', 'sensor_49', 'sensor_51']}, 'shape': {'rows': 220320, 'cols': 73}}}

Saved missingness_quarantine payload to Truth + Ledger.
Dropped: ['sensor_15', 'sensor_50']
global: 0.012254901960784314
normal: 0.010688120639732603
abnormal: 0.0
recovery: 0.03453754230848933
Final FEATURE_COLUMNS: 50
Final FEATURE_GROUPS: 1 groups
Dropped: 2 ['sensor_15', 'sensor_50']

2026-04-20 14:46:12,889 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:46:12.888975+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'step', 'step': 'build_silver_truth_record', 'message': 'Built and saved Silver truth record and stamped only truth lineage columns to dataframe.', 'why': None, 'consequence': None, 'data': {'silver_truth_hash': '7a3d006c17aa92eada073c87947cad4165af02c4e43b3eca859b4148a811560b', 'silver_parent_truth_hash': '72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976', 'silver_truth_path': '/workspace/artifacts/truths/silver/pump__silver__truth__7a3d006c17aa92eada073c87947cad4165af02c4e43b3eca859b4148a811560b.json', 'pipeline_mode': 'batch', 'process_run_id': 'silver_process__20260420T144546Z'}}
2026-04-20 14:46:12,900 | INFO | capstone.file_io | Saving DataFrame to Parquet: /workspace/data/silver/train/pump__silver__train.parquet
2026-04-20 14:46:15,052 | INFO | capstone.file_io | Saved: pump__silver__train.parquet | shape=(220320, 73) | columns=['meta__asset_id', 'meta__dataset', 'meta__episode_id', 'meta__event_id', 'meta__ingested_at_utc', 'meta__parent_truth_hash', 'meta__pipeline_mode', 'meta__record_id', 'meta__run_id', 'meta__source_file', 'meta__source_row_id', 'meta__split', 'meta__truth_hash', 'event_time', 'event_step', 'time_index', 'event_date', 'anomaly_flag', 'is_anomaly', 'is_normal', 'status_normal_value', 'sensor_00', 'sensor_01', 'sensor_02', 'sensor_03', 'sensor_04', 'sensor_05', 'sensor_06', 'sensor_07', 'sensor_08', 'sensor_09', 'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21', 'sensor_22', 'sensor_23', 'sensor_24', 'sensor_25', 'sensor_26', 'sensor_27', 'sensor_28', 'sensor_29', 'sensor_30', 'sensor_31', 'sensor_32', 'sensor_33', 'sensor_34', 'sensor_35', 'sensor_36', 'sensor_37', 'sensor_38', 'sensor_39', 'sensor_40', 'sensor_41', 'sensor_42', 'sensor_43', 'sensor_44', 'sensor_45', 'sensor_46', 'sensor_47', 'sensor_48', 'sensor_49', 'sensor_51', 'timestamp', 'machine_status']
2026-04-20 14:46:15,070 | INFO | capstone.file_io | Saved JSON: /workspace/artifacts/silver/pump/pump__silver__feature_registry.json
2026-04-20 14:46:15,073 | INFO | capstone.silver | LEDGER | {'ts_utc': '2026-04-20T14:46:15.073926+00:00', 'stage': 'silver', 'recipe': 'silver__clean__dataset__agnostic__v001', 'kind': 'step', 'step': 'silver_finalize_export', 'message': 'Finalized Silver export under the strict truth-store meta contract.', 'why': None, 'consequence': None, 'data': {'dataset_name': 'pump', 'silver_parquet_path': '/workspace/data/silver/train/pump__silver__train.parquet', 'feature_registry_path': '/workspace/artifacts/silver/pump/pump__silver__feature_registry.json', 'quality_info': {'total_rows': 220320, 'total_columns': 73, 'duplicate_row_count': 0, 'duplicate_event_id_count': 0, 'numeric_feature_count': 50, 'top_numeric_missingness_percent': {'sensor_51': 6.982116920842412, 'sensor_00': 4.633260711692085, 'sensor_07': 2.474128540305011, 'sensor_08': 2.3179920116194626, 'sensor_06': 2.177741466957153, 'sensor_09': 2.0856027596223674, 'sensor_01': 0.16748366013071894, 'sensor_30': 0.1184640522875817, 'sensor_29': 0.0326797385620915, 'sensor_32': 0.030864197530864196, 'sensor_17': 0.020878721859114015, 'sensor_18': 0.020878721859114015, 'sensor_22': 0.018609295570079884, 'sensor_25': 0.01633986928104575, 'sensor_16': 0.014070442992011621, 'sensor_38': 0.012254901960784314, 'sensor_39': 0.012254901960784314, 'sensor_40': 0.012254901960784314, 'sensor_41': 0.012254901960784314, 'sensor_42': 0.012254901960784314, 'sensor_43': 0.012254901960784314, 'sensor_44': 0.012254901960784314, 'sensor_45': 0.012254901960784314, 'sensor_46': 0.012254901960784314, 'sensor_47': 0.012254901960784314}, 'anomaly_rate_percent': 6.5740740740740735, 'anomaly_counts': {'0': 205836, '1': 14484}}, 'feature_set_id': 'feature_set__bea5fdd737ae53fcd80ca84cafcd0c40', 'feature_count': 50, 'silver_truth_hash': '7a3d006c17aa92eada073c87947cad4165af02c4e43b3eca859b4148a811560b', 'silver_parent_truth_hash': '72a94a9e57899cc4364af8a15ee451b148cffe19579a09f3fa18f27dfee70976', 'pipeline_mode': 'batch', 'process_run_id': 'silver_process__20260420T144546Z', 'shape': {'rows': 220320, 'cols': 73}}}

2026-04-20 14:46:27,940 | INFO | capstone.file_io | Loading JSON: /workspace/artifacts/truths/silver/pump__silver__truth__7a3d006c17aa92eada073c87947cad4165af02c4e43b3eca859b4148a811560b.json

Silver PreEDA lineage sanity check passed.

### EDA

In [ ]:
%run ./eda/EDA_Notebook_Pump_Silver_02_EDA.ipynb

## Gold

### Preprocessing

In [ ]:
%run ./experiments/EDA_Notebook_Pump_Gold_01_PreProcessing.ipynb

### Baseline

In [ ]:
%run ./experiments/EDA_Notebook_Pump_Gold_02_Baseline_Modeling.ipynb

### Cascade Defaults - Threshold, Threshold, Basic Alerts

In [ ]:
%run ./experiments/EDA_Notebook_Pump_Gold_03a_Cascade_Modeling.ipynb

### Cascade Tunable Stage 2 - Threshold, Tunable Threshold (Grid Search), Basic Alerts

In [ ]:
%run ./experiments/EDA_Notebook_Pump_Gold_03b_Cascade_Modeling.ipynb

### Cascade Enhanced Stage 3 Alerts - Threshold, Tunable Threshold (Grid Search), and Enhanced Stage 3 Alerts

In [ ]:
%run ./experiments/EDA_Notebook_Pump_Gold_03c_Cascade_Modeling.ipynb

### Model Performance Comparision

In [ ]:
%run ./experiments/EDA_Notebook_Pump_Gold_04_Comparision.ipynb

### Anomaly Detection and Predictive Maintenance Notebook

In [ ]:
%run ./experiments/EDA_Notebook_Pump_Gold_05_Anomaly_Detection.ipynb