In [ ]:
import os
import pandas as pd 

from utils.database.postgres import (
    get_engine_from_env, 
    read_sql_dataframe,
    execute_sql,
)

from utils.synthetic.pipeline.rebuild_comparison import build_rebuild_comparison_stage

from utils.core.env_helpers import (
    env_float, 
    env_int, 
    env_str
)

# Show every column regardless of count
pd.set_option('display.max_columns', None)

# Prevent columns from wrapping to a new line
pd.set_option('display.width', 1000)

# Optional: Prevent cell content inside columns from cutting off
pd.set_option('display.max_colwidth', None)

In [14]:
SCHEMA = env_str("CAPSTONE_SCHEMA", "capstone")

DATASET_ID = env_str(
    "SYNTHETIC_DATASET_ID",
    "pump_synthetic_v1",
    aliases=("DATASET_ID",),
)

RUN_ID = env_str(
    "SYNTHETIC_RUN_ID",
    "synthetic_run_001",
    aliases=("RUN_ID",),
)

NUMBER_OF_SENSORS = env_int("SYNTHETIC_SENSOR_COUNT", 52)

FLOAT_TOLERANCE = env_float(
    "SYNTHETIC_REBUILD_COMPARISON_FLOAT_TOLERANCE",
    1e-9,
)

OBSERVATION_WINDOW_SIZE = env_int(
    "SYNTHETIC_REBUILD_OBSERVATION_WINDOW_SIZE",
    2500,
)

PREMELT_SOURCE_TABLE_NAME = env_str(
    "SYNTHETIC_PREMELT_OBSERVATIONS_TABLE",
    "synthetic_observations_premelt_stage",
)

REBUILT_DESTINATION_TABLE_NAME = env_str(
    "SYNTHETIC_REBUILT_OBSERVATIONS_TABLE",
    "synthetic_sensor_observations_rebuilt_stage",
)

TARGET_TABLE_NAME = env_str(
    "SYNTHETIC_REBUILD_COMPARISON_TABLE",
    "synthetic_sensor_rebuild_comparison_stage",
)

print("Rebuild comparison config")
print("schema:", SCHEMA)
print("dataset id:", DATASET_ID)
print("run id:", RUN_ID)
print("premelt table:", PREMELT_SOURCE_TABLE_NAME)
print("rebuilt table:", REBUILT_DESTINATION_TABLE_NAME)
print("target table:", TARGET_TABLE_NAME)

Rebuild comparison config
schema: capstone
dataset id: pump_synthetic_v1
run id: synthetic_run_001
premelt table: synthetic_observations_premelt_stage
rebuilt table: synthetic_sensor_observations_rebuilt_stage
target table: synthetic_sensor_rebuild_comparison_stage

In [15]:
engine = get_engine_from_env()

----

In [17]:
comparison_result = build_rebuild_comparison_stage(
    engine=engine,
    schema=SCHEMA,
    premelt_table=PREMELT_SOURCE_TABLE_NAME,
    rebuilt_table=REBUILT_DESTINATION_TABLE_NAME,
    target_table=TARGET_TABLE_NAME,
    dataset_id=DATASET_ID,
    run_id=RUN_ID,
    n_sensors=NUMBER_OF_SENSORS,
    float_tolerance=FLOAT_TOLERANCE,
    observation_window_size=OBSERVATION_WINDOW_SIZE,
)

display(comparison_result)

[obs-window] 1 | observation_index 1 to 2,500
[obs-window] 2 | observation_index 2,501 to 5,000
[obs-window] 3 | observation_index 5,001 to 7,500
[obs-window] 4 | observation_index 7,501 to 10,000
[obs-window] 5 | observation_index 10,001 to 12,500
[obs-window] 6 | observation_index 12,501 to 15,000
[obs-window] 7 | observation_index 15,001 to 17,500
[obs-window] 8 | observation_index 17,501 to 20,000
[obs-window] 9 | observation_index 20,001 to 22,500
[obs-window] 10 | observation_index 22,501 to 25,000
[obs-window] 11 | observation_index 25,001 to 27,500
[obs-window] 12 | observation_index 27,501 to 30,000
[obs-window] 13 | observation_index 30,001 to 32,500
[obs-window] 14 | observation_index 32,501 to 35,000
[obs-window] 15 | observation_index 35,001 to 37,500
[obs-window] 16 | observation_index 37,501 to 40,000
[obs-window] 17 | observation_index 40,001 to 42,500
[obs-window] 18 | observation_index 42,501 to 45,000
[obs-window] 19 | observation_index 45,001 to 47,500
[obs-window] 20 | observation_index 47,501 to 50,000
[obs-window] 21 | observation_index 50,001 to 52,500
[obs-window] 22 | observation_index 52,501 to 55,000
[obs-window] 23 | observation_index 55,001 to 57,500
[obs-window] 24 | observation_index 57,501 to 60,000
[obs-window] 25 | observation_index 60,001 to 62,500
[obs-window] 26 | observation_index 62,501 to 65,000
[obs-window] 27 | observation_index 65,001 to 67,500
[obs-window] 28 | observation_index 67,501 to 70,000
[obs-window] 29 | observation_index 70,001 to 72,500
[obs-window] 30 | observation_index 72,501 to 75,000
[obs-window] 31 | observation_index 75,001 to 77,500
[obs-window] 32 | observation_index 77,501 to 80,000
[obs-window] 33 | observation_index 80,001 to 82,500
[obs-window] 34 | observation_index 82,501 to 85,000
[obs-window] 35 | observation_index 85,001 to 87,500
[obs-window] 36 | observation_index 87,501 to 90,000
[obs-window] 37 | observation_index 90,001 to 92,500
[obs-window] 38 | observation_index 92,501 to 95,000
[obs-window] 39 | observation_index 95,001 to 97,500
[obs-window] 40 | observation_index 97,501 to 100,000
[obs-window] 41 | observation_index 100,001 to 102,500
[obs-window] 42 | observation_index 102,501 to 105,000
[obs-window] 43 | observation_index 105,001 to 107,500
[obs-window] 44 | observation_index 107,501 to 110,000
[obs-window] 45 | observation_index 110,001 to 112,500
[obs-window] 46 | observation_index 112,501 to 115,000
[obs-window] 47 | observation_index 115,001 to 117,500
[obs-window] 48 | observation_index 117,501 to 120,000
[obs-window] 49 | observation_index 120,001 to 122,500
[obs-window] 50 | observation_index 122,501 to 125,000
[obs-window] 51 | observation_index 125,001 to 127,500
[obs-window] 52 | observation_index 127,501 to 130,000
[obs-window] 53 | observation_index 130,001 to 132,500
[obs-window] 54 | observation_index 132,501 to 135,000
[obs-window] 55 | observation_index 135,001 to 137,500
[obs-window] 56 | observation_index 137,501 to 140,000
[obs-window] 57 | observation_index 140,001 to 142,500
[obs-window] 58 | observation_index 142,501 to 145,000
[obs-window] 59 | observation_index 145,001 to 147,500
[obs-window] 60 | observation_index 147,501 to 150,000
[obs-window] 61 | observation_index 150,001 to 152,500
[obs-window] 62 | observation_index 152,501 to 155,000
[obs-window] 63 | observation_index 155,001 to 157,500
[obs-window] 64 | observation_index 157,501 to 160,000
[obs-window] 65 | observation_index 160,001 to 162,500
[obs-window] 66 | observation_index 162,501 to 165,000
[obs-window] 67 | observation_index 165,001 to 167,500
[obs-window] 68 | observation_index 167,501 to 170,000
[obs-window] 69 | observation_index 170,001 to 172,500
[obs-window] 70 | observation_index 172,501 to 175,000
[obs-window] 71 | observation_index 175,001 to 177,500
[obs-window] 72 | observation_index 177,501 to 180,000
[obs-window] 73 | observation_index 180,001 to 182,500
[obs-window] 74 | observation_index 182,501 to 185,000
[obs-window] 75 | observation_index 185,001 to 187,500
[obs-window] 76 | observation_index 187,501 to 190,000
[obs-window] 77 | observation_index 190,001 to 192,500
[obs-window] 78 | observation_index 192,501 to 195,000
[obs-window] 79 | observation_index 195,001 to 197,500
[obs-window] 80 | observation_index 197,501 to 200,000
[obs-window] 81 | observation_index 200,001 to 202,500
[obs-window] 82 | observation_index 202,501 to 205,000
[obs-window] 83 | observation_index 205,001 to 207,500
[obs-window] 84 | observation_index 207,501 to 210,000
[obs-window] 85 | observation_index 210,001 to 212,500
[obs-window] 86 | observation_index 212,501 to 215,000
[obs-window] 87 | observation_index 215,001 to 217,500
[obs-window] 88 | observation_index 217,501 to 220,000
[obs-window] 89 | observation_index 220,001 to 222,500
[obs-window] 90 | observation_index 222,501 to 225,000

{'status': 'built',
 'comparison_rows': 225000,
 'target_table': 'synthetic_sensor_rebuild_comparison_stage'}

----

In [19]:
summary_dataframe = read_sql_dataframe(
    engine,
    f"""
    SELECT
        COUNT(*) AS comparison_row_count,
        COUNT(*) FILTER (WHERE comparison_all_fields_match = TRUE) AS all_match_count,
        COUNT(*) FILTER (WHERE comparison_all_fields_match = FALSE) AS mismatch_count,
        MAX(comparison_mismatch_count) AS max_mismatch_count
    FROM "{SCHEMA}"."{TARGET_TABLE_NAME}"
    
    """,
)

display(summary_dataframe)

   comparison_row_count  all_match_count  mismatch_count  max_mismatch_count
0                225000           225000               0                   0

----

In [20]:
mismatch_dataframe = read_sql_dataframe(
    engine,
    f"""
    SELECT
        dataset_id,
        run_id,
        asset_id,
        observation_index,
        comparison_mismatch_count,
        comparison_notes,
        exists_in_original,
        exists_in_rebuilt,
        rebuilt_rebuild_sensor_count,
        rebuilt_rebuild_is_complete
    FROM "{SCHEMA}"."{TARGET_TABLE_NAME}"
    WHERE dataset_id = :dataset_id
      AND run_id = :run_id
      AND comparison_all_fields_match = FALSE
    ORDER BY observation_index
    LIMIT 50
    """,
    params={
        "dataset_id": DATASET_ID,
        "run_id": RUN_ID,
    },
)

display(mismatch_dataframe)

Empty DataFrame
Columns: [dataset_id, run_id, asset_id, observation_index, comparison_mismatch_count, comparison_notes, exists_in_original, exists_in_rebuilt, rebuilt_rebuild_sensor_count, rebuilt_rebuild_is_complete]
Index: []

-----

In [21]:
comparison_columns_dataframe = read_sql_dataframe(
    engine,
    """
    SELECT column_name
    FROM information_schema.columns
    WHERE table_schema = :schema_name
      AND table_name = :table_name
    ORDER BY ordinal_position
    """,
    params={
        "schema_name": SCHEMA,
        "table_name": TARGET_TABLE_NAME,
    },
)

match_columns = [
    column
    for column in comparison_columns_dataframe["column_name"].tolist()
    if column.startswith("match")
]

print("Match columns found:", len(match_columns))
display(pd.DataFrame({"match_column": match_columns}).head(100))

Match columns found: 58

                     match_column
0          match_generated_row_id
1              match_stream_state
2                     match_phase
3           match_meta_episode_id
4   match_meta_primary_fault_type
5            match_meta_magnitude
6                 match_sensor_00
7                 match_sensor_01
8                 match_sensor_02
9                 match_sensor_03
10                match_sensor_04
11                match_sensor_05
12                match_sensor_06
13                match_sensor_07
14                match_sensor_08
15                match_sensor_09
16                match_sensor_10
17                match_sensor_11
18                match_sensor_12
19                match_sensor_13
20                match_sensor_14
21                match_sensor_15
22                match_sensor_16
23                match_sensor_17
24                match_sensor_18
25                match_sensor_19
26                match_sensor_20
27                match_sensor_21
28                match_sensor_22
29                match_sensor_23
30                match_sensor_24
31                match_sensor_25
32                match_sensor_26
33                match_sensor_27
34                match_sensor_28
35                match_sensor_29
36                match_sensor_30
37                match_sensor_31
38                match_sensor_32
39                match_sensor_33
40                match_sensor_34
41                match_sensor_35
42                match_sensor_36
43                match_sensor_37
44                match_sensor_38
45                match_sensor_39
46                match_sensor_40
47                match_sensor_41
48                match_sensor_42
49                match_sensor_43
50                match_sensor_44
51                match_sensor_45
52                match_sensor_46
53                match_sensor_47
54                match_sensor_48
55                match_sensor_49
56                match_sensor_50
57                match_sensor_51

In [22]:
match_failure_sql_parts = [
    f"""
    SELECT
        '{column}' AS match_column,
        COUNT(*) FILTER (WHERE "{column}" = FALSE) AS failed_count,
        COUNT(*) FILTER (WHERE "{column}" = TRUE) AS passed_count
    FROM "{SCHEMA}"."{TARGET_TABLE_NAME}"
    WHERE dataset_id = :dataset_id
      AND run_id = :run_id
    """
    for column in match_columns
]

match_failure_summary_dataframe = read_sql_dataframe(
    engine,
    "\nUNION ALL\n".join(match_failure_sql_parts)
    + "\nORDER BY failed_count DESC, match_column",
    params={
        "dataset_id": DATASET_ID,
        "run_id": RUN_ID,
    },
)

display(match_failure_summary_dataframe)

                     match_column  failed_count  passed_count
0          match_generated_row_id             0        225000
1           match_meta_episode_id             0        225000
2            match_meta_magnitude             0        225000
3   match_meta_primary_fault_type             0        225000
4                     match_phase             0        225000
5                 match_sensor_00             0        225000
6                 match_sensor_01             0        225000
7                 match_sensor_02             0        225000
8                 match_sensor_03             0        225000
9                 match_sensor_04             0        225000
10                match_sensor_05             0        225000
11                match_sensor_06             0        225000
12                match_sensor_07             0        225000
13                match_sensor_08             0        225000
14                match_sensor_09             0        225000
15                match_sensor_10             0        225000
16                match_sensor_11             0        225000
17                match_sensor_12             0        225000
18                match_sensor_13             0        225000
19                match_sensor_14             0        225000
20                match_sensor_15             0        225000
21                match_sensor_16             0        225000
22                match_sensor_17             0        225000
23                match_sensor_18             0        225000
24                match_sensor_19             0        225000
25                match_sensor_20             0        225000
26                match_sensor_21             0        225000
27                match_sensor_22             0        225000
28                match_sensor_23             0        225000
29                match_sensor_24             0        225000
30                match_sensor_25             0        225000
31                match_sensor_26             0        225000
32                match_sensor_27             0        225000
33                match_sensor_28             0        225000
34                match_sensor_29             0        225000
35                match_sensor_30             0        225000
36                match_sensor_31             0        225000
37                match_sensor_32             0        225000
38                match_sensor_33             0        225000
39                match_sensor_34             0        225000
40                match_sensor_35             0        225000
41                match_sensor_36             0        225000
42                match_sensor_37             0        225000
43                match_sensor_38             0        225000
44                match_sensor_39             0        225000
45                match_sensor_40             0        225000
46                match_sensor_41             0        225000
47                match_sensor_42             0        225000
48                match_sensor_43             0        225000
49                match_sensor_44             0        225000
50                match_sensor_45             0        225000
51                match_sensor_46             0        225000
52                match_sensor_47             0        225000
53                match_sensor_48             0        225000
54                match_sensor_49             0        225000
55                match_sensor_50             0        225000
56                match_sensor_51             0        225000
57             match_stream_state             0        225000

In [23]:
episode_id_mismatch_sample_dataframe = read_sql_dataframe(
    engine,
    f"""
    SELECT
        dataset_id,
        run_id,
        asset_id,
        observation_index,
        original_meta_episode_id,
        rebuilt_meta_episode_id,
        match_meta_episode_id
    FROM "{SCHEMA}"."{TARGET_TABLE_NAME}"
    WHERE dataset_id = :dataset_id
      AND run_id = :run_id
      AND match_meta_episode_id = FALSE
    ORDER BY observation_index
    LIMIT 50
    """,
    params={
        "dataset_id": DATASET_ID,
        "run_id": RUN_ID,
    },
)

display(episode_id_mismatch_sample_dataframe)

Empty DataFrame
Columns: [dataset_id, run_id, asset_id, observation_index, original_meta_episode_id, rebuilt_meta_episode_id, match_meta_episode_id]
Index: []

---

In [24]:
observation_to_check = 1

detail_dataframe = read_sql_dataframe(
    engine,
    f"""
    SELECT *
    FROM "{SCHEMA}"."{TARGET_TABLE_NAME}"
    WHERE observation_index = {int(observation_to_check)}
    """,
)

display(detail_dataframe)

,dataset_id,run_id,asset_id,observation_index,exists_in_original,exists_in_rebuilt,comparison_mismatch_count,comparison_all_fields_match,comparison_notes,comparison_completed_at,rebuilt_rebuild_sensor_count,rebuilt_rebuild_is_complete,original_generated_row_id,original_batch_id,original_row_in_batch,original_global_cycle_id,original_stream_state,original_phase,original_created_at,original_meta_episode_id,original_meta_primary_fault_type,original_meta_magnitude,original_is_telemetry_event,original_telemetry_event_type,original_producer_send_attempt,original_meta_is_fault_episode,original_meta_phase_truth,original_meta_primary_sensor,original_meta_primary_magnitude,original_meta_primary_sensor_abs_zscore,original_meta_primary_sensor_threshold_crossed,original_meta_fault_onset_truth_flag,original_meta_fault_onset_truth_row,original_meta_failure_truth_flag,original_meta_failure_truth_row,original_meta_observable_onset_flag,original_meta_observable_onset_row,original_meta_buildup_progress,original_meta_rows_until_failure,original_meta_rows_since_truth_onset,original_meta_rows_since_observable_onset,original_sensor_00,original_sensor_01,original_sensor_02,original_sensor_03,original_sensor_04,original_sensor_05,original_sensor_06,original_sensor_07,original_sensor_08,original_sensor_09,original_sensor_10,original_sensor_11,original_sensor_12,original_sensor_13,original_sensor_14,original_sensor_15,original_sensor_16,original_sensor_17,original_sensor_18,original_sensor_19,original_sensor_20,original_sensor_21,original_sensor_22,original_sensor_23,original_sensor_24,original_sensor_25,original_sensor_26,original_sensor_27,original_sensor_28,original_sensor_29,original_sensor_30,original_sensor_31,original_sensor_32,original_sensor_33,original_sensor_34,original_sensor_35,original_sensor_36,original_sensor_37,original_sensor_38,original_sensor_39,original_sensor_40,original_sensor_41,original_sensor_42,original_sensor_43,original_sensor_44,original_sensor_45,original_sensor_46,original_sensor_47,original_sensor_48,original_sensor_49,original_sensor_50,original_sensor_51,rebuilt_observation_timestamp,rebuilt_generated_row_id,rebuilt_stream_state,rebuilt_phase,rebuilt_meta_episode_id,rebuilt_meta_primary_fault_type,rebuilt_meta_magnitude,rebuilt_rebuild_completed_at,rebuilt_rebuild_notes,rebuilt_sensor_00,rebuilt_sensor_01,rebuilt_sensor_02,rebuilt_sensor_03,rebuilt_sensor_04,rebuilt_sensor_05,rebuilt_sensor_06,rebuilt_sensor_07,rebuilt_sensor_08,rebuilt_sensor_09,rebuilt_sensor_10,rebuilt_sensor_11,rebuilt_sensor_12,rebuilt_sensor_13,rebuilt_sensor_14,rebuilt_sensor_15,rebuilt_sensor_16,rebuilt_sensor_17,rebuilt_sensor_18,rebuilt_sensor_19,rebuilt_sensor_20,rebuilt_sensor_21,rebuilt_sensor_22,rebuilt_sensor_23,rebuilt_sensor_24,rebuilt_sensor_25,rebuilt_sensor_26,rebuilt_sensor_27,rebuilt_sensor_28,rebuilt_sensor_29,rebuilt_sensor_30,rebuilt_sensor_31,rebuilt_sensor_32,rebuilt_sensor_33,rebuilt_sensor_34,rebuilt_sensor_35,rebuilt_sensor_36,rebuilt_sensor_37,rebuilt_sensor_38,rebuilt_sensor_39,rebuilt_sensor_40,rebuilt_sensor_41,rebuilt_sensor_42,rebuilt_sensor_43,rebuilt_sensor_44,rebuilt_sensor_45,rebuilt_sensor_46,rebuilt_sensor_47,rebuilt_sensor_48,rebuilt_sensor_49,rebuilt_sensor_50,rebuilt_sensor_51,match_generated_row_id,match_stream_state,match_phase,match_meta_episode_id,match_meta_primary_fault_type,match_meta_magnitude,match_sensor_00,match_sensor_01,match_sensor_02,match_sensor_03,match_sensor_04,match_sensor_05,match_sensor_06,match_sensor_07,match_sensor_08,match_sensor_09,match_sensor_10,match_sensor_11,match_sensor_12,match_sensor_13,match_sensor_14,match_sensor_15,match_sensor_16,match_sensor_17,match_sensor_18,match_sensor_19,match_sensor_20,match_sensor_21,match_sensor_22,match_sensor_23,match_sensor_24,match_sensor_25,match_sensor_26,match_sensor_27,match_sensor_28,match_sensor_29,match_sensor_30,match_sensor_31,match_sensor_32,match_sensor_33,match_sensor_34,match_sensor_35,match_sensor_36,match_sensor_37,match_sensor_38,match_sensor_39,match_sensor_40,match_sensor_41,match_sensor_42,match_sensor_43,match_sensor_44,match_sensor_45,match_sensor_46,match_sensor_47,match_sensor_48,match_sensor_49,match_sensor_50,match_sensor_51
0,pump_synthetic_v1,synthetic_run_001,pump_asset_001,1,True,True,0,True,None,2026-05-29 00:47:34.831973+00:00,52,True,synthetic_run_001_obs_000000000001,1,0,1,normal,normal,2026-05-24 23:54:01.146754+00:00,0,drift_down,1.2125,False,None,1,False,normal,sensor_43,1.2125,0.655825,False,False,None,False,None,False,None,0.0,None,None,None,2.344329,48.327756,53.57595,43.424633,617.854335,62.387073,13.849883,16.283766,14.495136,15.464113,51.184484,53.793786,29.128108,3.515049,417.900729,None,463.965987,464.894769,2.591281,667.840901,404.621552,883.667093,525.141842,1025.436166,629.044677,740.596262,853.54296,678.172172,895.17918,939.340667,832.206421,1196.597451,948.540609,539.675897,123.837189,359.725173,418.667752,50.398176,48.112895,37.670573,78.411188,33.787299,35.658784,47.973746,74.331914,59.387182,44.227766,37.686628,40.089498,43.412712,188.45056,300.841897,2026-04-16 00:00:00+00:00,synthetic_run_001_obs_000000000001,normal,normal,0,drift_down,1.2125,2026-05-27 14:01:45.483771+00:00,None,2.344329,48.327756,53.57595,43.424633,617.854335,62.387073,13.849883,16.283766,14.495136,15.464113,51.184484,53.793786,29.128108,3.515049,417.900729,None,463.965987,464.894769,2.591281,667.840901,404.621552,883.667093,525.141842,1025.436166,629.044677,740.596262,853.54296,678.172172,895.17918,939.340667,832.206421,1196.597451,948.540609,539.675897,123.837189,359.725173,418.667752,50.398176,48.112895,37.670573,78.411188,33.787299,35.658784,47.973746,74.331914,59.387182,44.227766,37.686628,40.089498,43.412712,188.45056,300.841897,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

----

In [25]:
stage_10_final_validation_dataframe = read_sql_dataframe(
    engine,
    f"""
    SELECT
        COUNT(*) AS comparison_row_count,
        COUNT(*) FILTER (WHERE comparison_all_fields_match = TRUE) AS all_fields_match_count,
        COUNT(*) FILTER (WHERE comparison_all_fields_match = FALSE) AS mismatch_row_count,
        COUNT(*) FILTER (WHERE exists_in_original = TRUE AND exists_in_rebuilt = FALSE) AS missing_from_rebuilt_count,
        COUNT(*) FILTER (WHERE exists_in_original = FALSE AND exists_in_rebuilt = TRUE) AS missing_from_original_count,
        MAX(comparison_mismatch_count) AS max_mismatch_count,
        (
            COUNT(*) = 225000
            AND COUNT(*) FILTER (WHERE comparison_all_fields_match = TRUE) = 225000
            AND COUNT(*) FILTER (WHERE comparison_all_fields_match = FALSE) = 0
            AND COUNT(*) FILTER (WHERE exists_in_original = TRUE AND exists_in_rebuilt = FALSE) = 0
            AND COUNT(*) FILTER (WHERE exists_in_original = FALSE AND exists_in_rebuilt = TRUE) = 0
        ) AS ready_for_stage_11
    FROM "{SCHEMA}"."{TARGET_TABLE_NAME}"
    WHERE dataset_id = :dataset_id
      AND run_id = :run_id
    """,
    params={
        "dataset_id": DATASET_ID,
        "run_id": RUN_ID,
    },
)

display(stage_10_final_validation_dataframe)

   comparison_row_count  all_fields_match_count  mismatch_row_count  missing_from_rebuilt_count  missing_from_original_count  max_mismatch_count  ready_for_stage_11
0                225000                  225000                   0                           0                            0                   0                True

In [26]:
import utils.synthetic.pipeline.rebuild_comparison as rebuild_comparison_module

print(rebuild_comparison_module.__file__)
print(rebuild_comparison_module._compare_scalar(0, "0"))
print(rebuild_comparison_module._compare_scalar(0.0, "0"))
print(rebuild_comparison_module._compare_scalar("0", "0"))

/workspace/utils/synthetic/pipeline/rebuild_comparison.py
True
True
True

In [ ]:
'''
execute_sql(
    engine,
    f"""
    DROP TABLE IF EXISTS "{SCHEMA}"."{TARGET_TABLE_NAME}" CASCADE
    """
)

print(f"Dropped {SCHEMA}.{TARGET_TABLE_NAME}")
'''

Dropped capstone.synthetic_sensor_rebuild_comparison_stage

In [27]:
# Dispose Engine
engine.dispose()